In [11]:
def greet(name):
    print(f"Hello, {name}! Hope you're having a great day.")

greet("Ahsan")

Hello, Ahsan! Hope you're having a great day.

In [13]:
def addNumbers(a, b):
    sumResult = a + b
    return sumResult

total = addNumbers(11, 9)
print(f"The total is: {total}")

The total is: 20

In [ ]:
class userProfile:
    def commaCleaner(self,price):
        price.replace(",","")
    def currencyCleaner(self,currency):
        currency.replace("$","")

In [15]:
class User:
    def __init__(self, first_name, last_name):
        self.first_name = first_name
        self.last_name = last_name
    def getFullName(self):
        return f"{self.first_name} {self.last_name}"
    def greeting(self):
        print(f"Welcome back, {self.getFullName()}!")
user1 = User("Ahsan", "Khan")
print(user1.first_name)
user1.greeting()

Ahsan
Welcome back, Ahsan Khan!

In [1]:
def addition(n1 , n2):
    s = n1 + n2
    return s

In [2]:
class userProfile:
    def commCleaner(self,price):
        price.replace(",","")
    def currencyCleaner(self,currency):
        currency.replace("$","")

In [5]:
class userProfile:
    def __init__(self,userName,userAge):
        self.userName = userName
        self.userAge = userAge


    def addLastName(self,lastName):
        self.userName = self.userName + " " + lastName
    def printUserName(self):
        print(self.userName)
    def printUserAge(self):
        print(f"{self.userName} is {20-18}")
    def printUserAddress(self):
        print(f"{self.userName} lives in New York")

In [7]:
u = userProfile("Ahsan",25)
u.addLastName("Jam")
u.printUserName()
u.printUserAge()
u.printUserAddress()

Ahsan Jam
Ahsan Jam is 2
Ahsan Jam lives in New York

In [8]:
class pclass:

    def parentClassFunction(self):
        print("this function is from parent class")

class cClass(pclass):

    def childClassFunction (self):
        print("this function is from child class")

Child = cClass()
Child.parentClassFunction()
Child.childClassFunction()

this function is from parent class
this function is from child class

In [9]:
class parentClass:
    def __init__(self,_name):
        self.__name = _name

    def publicFunc(self):
        print("this function is from parent class")
    def privateFunc(self):
        print("this function is from parent class")

class childClass(parentClass):
    def __init__(self,name,age):
        super().__init__(name)
        self.age = age

    def chilClassFunc(self):
        print("this function is from child class")
class grandChildClass(childClass):
    def __init__(self,name,age):
        super().__init__(name,age)
        self.age = age

In [10]:
ca = grandChildClass("Ahmad",20)
ca.privateFunc()

this function is from parent class

In [11]:
class parentClass1:
    def polyFunction(self):
        print("this function is from parent class")
class childClass1(parentClass1):
    def polyFunction(self):
        print("this function is from child class")
c = childClass1()
c.polyFunction()

this function is from child class

In [12]:
#Encapsulation
#Inheritence
#Polymorphism
#Access modifiers

In [17]:
class UserProfile:
    def __init__(self,name,age,gender):
        self.name = name
        self.age = age
        self.gender = gender

In [18]:
n = UserProfile("Ahsan",20,"Male")
print(n.name,n.age,n.gender)

Ahsan 20 Male

In [29]:
class userProfile:
    def __init__(self,userName,userAge,userGender):
        self.userName = userName
        self.userAge = userAge
        self.userGender = userGender


    def addLastName(self,lastName):
        self.userName = self.userName + " " + lastName
    def printUserName(self):
        print(self.userName)
    def printUserAge(self):
        print(f"{self.userName} is {20-18}")
    def printUserAddress(self):
        print(f"{self.userName} lives in New York")
    def printUserGender(self):
        print(f"{self.userName} is Male")

In [30]:
u = userProfile("Ahsan",25,"Male")
u.addLastName("Jam")
u.printUserName()
u.printUserAge()
u.printUserAddress()
u.printUserGender()

Ahsan Jam
Ahsan Jam is 2
Ahsan Jam lives in New York
Ahsan Jam is Male

In [1]:
import requests as r
from bs4 import BeautifulSoup as bs
import pandas as pd

response = r.get("https://www.scrapethissite.com/pages/simple/")
pageSource = response.text
with open("PageSource.txt","w",encoding="utf-8") as f:
  f.write(pageSource)

In [3]:
from bs4 import BeautifulSoup as bs
import pandas as pd
with open("PageSource.txt","r",encoding="utf-8") as f:
    sourceCode = f.read()
    s = bs(sourceCode,"html.parser")
    # s = s.prettify()
    countryData ={"Country Name": [], "Country Capital": [], "Country Population": [], "Country Area": []}
    countryNames = s.find_all("h3",{"class":"country-name"})
    countrycapitals = s.find_all("span", {"class": "country-capital"})
    countrypopulation = s.find_all("span", {"class": "country-population"})
    countryArea = s.find_all("span", {"class": "country-area"})
    for i in range(len(countryNames)):
        countryData["Country Name"].append(countryNames[i].text.strip())
        countryData["Country Capital"].append(countrycapitals[i].text.strip())
        countryData["Country Population"].append(countrypopulation[i].text.strip())
        countryData["Country Area"].append(countryArea[i].text.strip())

In [4]:
countryInfodf = pd.DataFrame(countryData)

In [5]:
countryInfodf

             Country Name   Country Capital Country Population Country Area
0                 Andorra  Andorra la Vella              84000        468.0
1    United Arab Emirates         Abu Dhabi            4975593      82880.0
2             Afghanistan             Kabul           29121286     647500.0
3     Antigua and Barbuda        St. John's              86754        443.0
4                Anguilla        The Valley              13254        102.0
..                    ...               ...                ...          ...
245                 Yemen             Sanaa           23495361     527970.0
246               Mayotte         Mamoudzou             159042        374.0
247          South Africa          Pretoria           49000000    1219912.0
248                Zambia            Lusaka           13460305     752614.0
249              Zimbabwe            Harare           11651858     390580.0

[250 rows x 4 columns]

In [6]:
countryInfodf.to_csv("CountryInfo.csv",index=False)

In [7]:
# Load the CSV file
df = pd.read_csv('CountryInfo.csv')

# Remove duplicate rows
df_cleaned = df.drop_duplicates()

# Save the result back to a CSV
df_cleaned.to_csv('CountryInfo.csv', index=False)

In [8]:
countryInfodf

             Country Name   Country Capital Country Population Country Area
0                 Andorra  Andorra la Vella              84000        468.0
1    United Arab Emirates         Abu Dhabi            4975593      82880.0
2             Afghanistan             Kabul           29121286     647500.0
3     Antigua and Barbuda        St. John's              86754        443.0
4                Anguilla        The Valley              13254        102.0
..                    ...               ...                ...          ...
245                 Yemen             Sanaa           23495361     527970.0
246               Mayotte         Mamoudzou             159042        374.0
247          South Africa          Pretoria           49000000    1219912.0
248                Zambia            Lusaka           13460305     752614.0
249              Zimbabwe            Harare           11651858     390580.0

[250 rows x 4 columns]

In [9]:
import requests as r
from bs4 import BeautifulSoup as bs


response = r.get("https://www.deckshop.pro/card/list")
pageSource = response.text
with open("ClashRoyal.txt","w",encoding="utf-8") as f:
  f.write(pageSource)

In [18]:
from bs4 import BeautifulSoup as bs
import pandas as pd
with open("ClashRoyal.txt","r",encoding="utf-8") as f:
    sourceCode = f.read()
    s = bs(sourceCode,"html.parser")
    # s = s.prettify()

    cardName = s.find_all("img",{"class":"card"})

    urlsOnlyCards =[]
    for eachUrl in cardName:
        urlsOnlyCards.append(eachUrl.get("src"))
    print(urlsOnlyCards)

['/img/card_ed_evo/Skellies.png', '/img/card_ed_evo/IceSpirit.png', '/img/card_ed_evo/Bomber.png', '/img/card_ed_evo/Bats.png', '/img/card_ed_evo/Zap.png', '/img/card_ed_evo/Snowball.png', '/img/card_ed_evo/Archers.png', '/img/card_ed_evo/Knight.png', '/img/card_ed_evo/Cannon.png', '/img/card_ed_evo/SkellyBarrel.png', '/img/card_ed_evo/Firecracker.png', '/img/card_ed_evo/Mortar.png', '/img/card_ed_evo/Tesla.png', '/img/card_ed_evo/Barbs.png', '/img/card_ed_evo/RG.png', '/img/card_ed_evo/RoyalRecruits.png', '/img/card_ed_evo/DartGob.png', '/img/card_ed_evo/Musk.png', '/img/card_ed_evo/GoblinCage.png', '/img/card_ed_evo/Valk.png', '/img/card_ed_evo/Ram.png', '/img/card_ed_evo/Furnace.png', '/img/card_ed_evo/Wiz.png', '/img/card_ed_evo/RoyalHogs.png', '/img/card_ed_evo/WallBreakers.png', '/img/card_ed_evo/Barrel.png', '/img/card_ed_evo/Skarmy.png', '/img/card_ed_evo/BabyD.png', '/img/card_ed_evo/Hunter.png', '/img/card_ed_evo/GoblinDrill.png', '/img/card_ed_evo/Witch.png', '/img/card_ed_evo/eDragon.png', '/img/card_ed_evo/Exe.png', '/img/card_ed_evo/GobGiant.png', '/img/card_ed_evo/PEKKA.png', '/img/card_ed_evo/Ghost.png', '/img/card_ed_evo/InfernoD.png', '/img/card_ed_evo/Lumber.png', '/img/card_ed_evo/MegaKnight.png', '/img/card_ed_hero/Gobs.png', '/img/card_ed_hero/Knight.png', '/img/card_ed_hero/IceGolem.png', '/img/card_ed_hero/MM.png', '/img/card_ed_hero/MP.png', '/img/card_ed_hero/Musk.png', '/img/card_ed_hero/Giant.png', '/img/card_ed_hero/Wiz.png', '/img/card_ed_hero/BarbBarrel.png', '/img/card_ed_hero/MagicArcher.png', '/img/card_ed/LittlePrince.png', '/img/card_ed/GoldenKnight.png', '/img/card_ed/SkeletonKing.png', '/img/card_ed/MightyMiner.png', '/img/card_ed/ArcherQueen.png', '/img/card_ed/Goblinstein.png', '/img/card_ed/Monk.png', '/img/card_ed/BossBandit.png', '/img/card_ed/Log.png', '/img/card_ed/Miner.png', '/img/card_ed/Princess.png', '/img/card_ed/IceWiz.png', '/img/card_ed/Ghost.png', '/img/card_ed/Bandit.png', '/img/card_ed/Fisherman.png', '/img/card_ed/eWiz.png', '/img/card_ed/InfernoD.png', '/img/card_ed/Phoenix.png', '/img/card_ed/MagicArcher.png', '/img/card_ed/Lumber.png', '/img/card_ed/NightWitch.png', '/img/card_ed/MotherWitch.png', '/img/card_ed/RamRider.png', '/img/card_ed/Graveyard.png', '/img/card_ed/GoblinMachine.png', '/img/card_ed/Sparky.png', '/img/card_ed/SpiritEmpress.png', '/img/card_ed/MegaKnight.png', '/img/card_ed/Lava.png', '/img/card_ed/Mirror.png', '/img/card_ed/BarbBarrel.png', '/img/card_ed/WallBreakers.png', '/img/card_ed/GoblinCurse.png', '/img/card_ed/Rage.png', '/img/card_ed/Barrel.png', '/img/card_ed/Guards.png', '/img/card_ed/Skarmy.png', '/img/card_ed/Vines.png', '/img/card_ed/Clone.png', '/img/card_ed/Tornado.png', '/img/card_ed/Void.png', '/img/card_ed/BabyD.png', '/img/card_ed/DarkPrince.png', '/img/card_ed/Freeze.png', '/img/card_ed/Poison.png', '/img/card_ed/RuneGiant.png', '/img/card_ed/Hunter.png', '/img/card_ed/GoblinDrill.png', '/img/card_ed/Witch.png', '/img/card_ed/Balloon.png', '/img/card_ed/Prince.png', '/img/card_ed/eDragon.png', '/img/card_ed/Bowler.png', '/img/card_ed/Exe.png', '/img/card_ed/CannonCart.png', '/img/card_ed/GiantSkelly.png', '/img/card_ed/Lightning.png', '/img/card_ed/GobGiant.png', '/img/card_ed/XBow.png', '/img/card_ed/PEKKA.png', '/img/card_ed/ElectroGiant.png', '/img/card_ed/Golem.png', '/img/card_ed/HealSpirit.png', '/img/card_ed/IceGolem.png', '/img/card_ed/SuspiciousBush.png', '/img/card_ed/Tombstone.png', '/img/card_ed/MM.png', '/img/card_ed/DartGob.png', '/img/card_ed/Earthquake.png', '/img/card_ed/ElixirGolem.png', '/img/card_ed/Fireball.png', '/img/card_ed/MP.png', '/img/card_ed/Musk.png', '/img/card_ed/GoblinCage.png', '/img/card_ed/GobHut.png', '/img/card_ed/Valk.png', '/img/card_ed/Ram.png', '/img/card_ed/BombTower.png', '/img/card_ed/FlyingMachine.png', '/img/card_ed/Hog.png', '/img/card_ed/BattleHealer.png', '/img/card_ed/Furnace.png', '/img/card_ed/Zappies.png', '/img/card_ed/GoblinDemolisher.png', '/img/card_ed/Giant.png', '/img/card_ed/Inferno.png', '/img/card_ed/Wiz.png', '/img/card_ed/RoyalHogs.png', '/img/card_ed/Rocket.png', '/img/card_ed/BarbHut.png', '/img/card_ed/Pump.png', '/img/card_ed/3M.png', '/img/card_ed/Skellies.png', '/img/card_ed/ElectroSpirit.png', '/img/card_ed/FireSpirit.png', '/img/card_ed/IceSpirit.png', '/img/card_ed/Gobs.png', '/img/card_ed/SpearGobs.png', '/img/card_ed/Bomber.png', '/img/card_ed/Bats.png', '/img/card_ed/Zap.png', '/img/card_ed/Snowball.png', '/img/card_ed/Berserker.png', '/img/card_ed/Archers.png', '/img/card_ed/Arrows.png', '/img/card_ed/Knight.png', '/img/card_ed/Minions.png', '/img/card_ed/Cannon.png', '/img/card_ed/GobGang.png', '/img/card_ed/SkellyBarrel.png', '/img/card_ed/Firecracker.png', '/img/card_ed/RoyalDelivery.png', '/img/card_ed/SkeletonDragons.png', '/img/card_ed/Mortar.png', '/img/card_ed/Tesla.png', '/img/card_ed/Barbs.png', '/img/card_ed/Horde.png', '/img/card_ed/Rascals.png', '/img/card_ed/RG.png', '/img/card_ed/eBarbs.png', '/img/card_ed/RoyalRecruits.png', '/img/c/Skellies.png', '/img/c/ElectroSpirit.png', '/img/c/FireSpirit.png', '/img/c/IceSpirit.png', '/img/c/HealSpirit.png', '/img/c/Gobs.png', '/img/c/SpearGobs.png', '/img/c/Bomber.png', '/img/c/Bats.png', '/img/c/Zap.png', '/img/c/Snowball.png', '/img/c/Berserker.png', '/img/c/IceGolem.png', '/img/c/SuspiciousBush.png', '/img/c/BarbBarrel.png', '/img/c/WallBreakers.png', '/img/c/GoblinCurse.png', '/img/c/Rage.png', '/img/c/Log.png', '/img/c/Archers.png', '/img/c/Arrows.png', '/img/c/Knight.png', '/img/c/Minions.png', '/img/c/Cannon.png', '/img/c/GobGang.png', '/img/c/SkellyBarrel.png', '/img/c/Firecracker.png', '/img/c/RoyalDelivery.png', '/img/c/Tombstone.png', '/img/c/MM.png', '/img/c/DartGob.png', '/img/c/Earthquake.png', '/img/c/ElixirGolem.png', '/img/c/Barrel.png', '/img/c/Guards.png', '/img/c/Skarmy.png', '/img/c/Vines.png', '/img/c/Clone.png', '/img/c/Tornado.png', '/img/c/Void.png', '/img/c/Miner.png', '/img/c/Princess.png', '/img/c/IceWiz.png', '/img/c/Ghost.png', '/img/c/Bandit.png', '/img/c/Fisherman.png', '/img/c/LittlePrince.png', '/img/c/SkeletonDragons.png', '/img/c/Mortar.png', '/img/c/Tesla.png', '/img/c/Fireball.png', '/img/c/MP.png', '/img/c/Musk.png', '/img/c/GoblinCage.png', '/img/c/GobHut.png', '/img/c/Valk.png', '/img/c/Ram.png', '/img/c/BombTower.png', '/img/c/FlyingMachine.png', '/img/c/Hog.png', '/img/c/BattleHealer.png', '/img/c/Furnace.png', '/img/c/Zappies.png', '/img/c/GoblinDemolisher.png', '/img/c/BabyD.png', '/img/c/DarkPrince.png', '/img/c/Freeze.png', '/img/c/Poison.png', '/img/c/RuneGiant.png', '/img/c/Hunter.png', '/img/c/GoblinDrill.png', '/img/c/eWiz.png', '/img/c/InfernoD.png', '/img/c/Phoenix.png', '/img/c/MagicArcher.png', '/img/c/Lumber.png', '/img/c/NightWitch.png', '/img/c/MotherWitch.png', '/img/c/GoldenKnight.png', '/img/c/SkeletonKing.png', '/img/c/MightyMiner.png', '/img/c/Barbs.png', '/img/c/Horde.png', '/img/c/Rascals.png', '/img/c/Giant.png', '/img/c/Inferno.png', '/img/c/Wiz.png', '/img/c/RoyalHogs.png', '/img/c/Witch.png', '/img/c/Balloon.png', '/img/c/Prince.png', '/img/c/eDragon.png', '/img/c/Bowler.png', '/img/c/Exe.png', '/img/c/CannonCart.png', '/img/c/RamRider.png', '/img/c/Graveyard.png', '/img/c/GoblinMachine.png', '/img/c/ArcherQueen.png', '/img/c/Goblinstein.png', '/img/c/Monk.png', '/img/c/RG.png', '/img/c/eBarbs.png', '/img/c/Rocket.png', '/img/c/BarbHut.png', '/img/c/Pump.png', '/img/c/GiantSkelly.png', '/img/c/Lightning.png', '/img/c/GobGiant.png', '/img/c/XBow.png', '/img/c/Sparky.png', '/img/c/SpiritEmpress.png', '/img/c/BossBandit.png', '/img/c/RoyalRecruits.png', '/img/c/PEKKA.png', '/img/c/ElectroGiant.png', '/img/c/MegaKnight.png', '/img/c/Lava.png', '/img/c/Golem.png', '/img/c/3M.png', '/img/card_ed/Zap.png', '/img/card_ed/Snowball.png', '/img/card_ed/Arrows.png', '/img/card_ed/RoyalDelivery.png', '/img/card_ed/Earthquake.png', '/img/card_ed/Fireball.png', '/img/card_ed/Rocket.png', '/img/card_ed/Mirror.png', '/img/card_ed/BarbBarrel.png', '/img/card_ed/GoblinCurse.png', '/img/card_ed/Rage.png', '/img/card_ed/Barrel.png', '/img/card_ed/Vines.png', '/img/card_ed/Clone.png', '/img/card_ed/Tornado.png', '/img/card_ed/Void.png', '/img/card_ed/Freeze.png', '/img/card_ed/Poison.png', '/img/card_ed/Lightning.png', '/img/card_ed/Log.png', '/img/card_ed/Graveyard.png', '/img/card_ed/Zap.png', '/img/card_ed/Snowball.png', '/img/card_ed/Arrows.png', '/img/card_ed/RoyalDelivery.png', '/img/card_ed/Earthquake.png', '/img/card_ed/Fireball.png', '/img/card_ed/Rocket.png', '/img/card_ed/BarbBarrel.png', '/img/card_ed/GoblinCurse.png', '/img/card_ed/Rage.png', '/img/card_ed/Vines.png', '/img/card_ed/Tornado.png', '/img/card_ed/Void.png', '/img/card_ed/Freeze.png', '/img/card_ed/Poison.png', '/img/card_ed/Lightning.png', '/img/card_ed/Log.png', '/img/card_ed/Cannon.png', '/img/card_ed/Mortar.png', '/img/card_ed/Tesla.png', '/img/card_ed/Tombstone.png', '/img/card_ed/GoblinCage.png', '/img/card_ed/GobHut.png', '/img/card_ed/BombTower.png', '/img/card_ed/Inferno.png', '/img/card_ed/BarbHut.png', '/img/card_ed/Pump.png', '/img/card_ed/GoblinDrill.png', '/img/card_ed/XBow.png', '/img/card_ed/Cannon.png', '/img/card_ed/Tesla.png', '/img/card_ed/BombTower.png', '/img/card_ed/Inferno.png', '/img/card_ed/Mortar.png', '/img/card_ed/XBow.png', '/img/card_ed/Tombstone.png', '/img/card_ed/GobHut.png', '/img/card_ed/BarbHut.png', '/img/card_ed/GoblinDrill.png', '/img/card_ed/Skellies.png', '/img/card_ed/Gobs.png', '/img/card_ed/Berserker.png', '/img/card_ed/GobGang.png', '/img/card_ed/Barbs.png', '/img/card_ed/Rascals.png', '/img/card_ed/ElixirGolem.png', '/img/card_ed/MP.png', '/img/card_ed/GoblinCage.png', '/img/card_ed/BarbBarrel.png', '/img/card_ed/Barrel.png', '/img/card_ed/Skarmy.png', '/img/card_ed/GiantSkelly.png', '/img/card_ed/Bandit.png', '/img/card_ed/Lumber.png', '/img/card_ed/Graveyard.png', '/img/card_ed/BossBandit.png', '/img/card_ed/Bats.png', '/img/card_ed/Knight.png', '/img/card_ed/eBarbs.png', '/img/card_ed/Valk.png', '/img/card_ed/DarkPrince.png', '/img/card_ed/RuneGiant.png', '/img/card_ed/GobGiant.png', '/img/card_ed/PEKKA.png', '/img/card_ed/ElectroGiant.png', '/img/card_ed/Miner.png', '/img/card_ed/Ghost.png', '/img/card_ed/Fisherman.png', '/img/card_ed/GoblinMachine.png', '/img/card_ed/SpiritEmpress.png', '/img/card_ed/MegaKnight.png', '/img/card_ed/GoldenKnight.png', '/img/card_ed/SkeletonKing.png', '/img/card_ed/Goblinstein.png', '/img/card_ed/Monk.png', '/img/card_ed/Minions.png', '/img/card_ed/RoyalDelivery.png', '/img/card_ed/Horde.png', '/img/card_ed/RoyalRecruits.png', '/img/card_ed/MM.png', '/img/card_ed/BattleHealer.png', '/img/card_ed/Guards.png', '/img/card_ed/Prince.png', '/img/card_ed/Phoenix.png', '/img/card_ed/NightWitch.png', '/img/card_ed/MightyMiner.png', '/img/card_ed/SpearGobs.png', '/img/card_ed/Bomber.png', '/img/card_ed/Archers.png', '/img/card_ed/Cannon.png', '/img/card_ed/GobGang.png', '/img/card_ed/Firecracker.png', '/img/card_ed/SkeletonDragons.png', '/img/card_ed/Rascals.png', '/img/card_ed/DartGob.png', '/img/card_ed/Musk.png', '/img/card_ed/GobHut.png', '/img/card_ed/FlyingMachine.png', '/img/card_ed/Furnace.png', '/img/card_ed/Zappies.png', '/img/card_ed/GoblinDemolisher.png', '/img/card_ed/Wiz.png', '/img/card_ed/3M.png', '/img/card_ed/BabyD.png', '/img/card_ed/Hunter.png', '/img/card_ed/Witch.png', '/img/card_ed/eDragon.png', '/img/card_ed/Bowler.png', '/img/card_ed/Exe.png', '/img/card_ed/CannonCart.png', '/img/card_ed/GobGiant.png', '/img/card_ed/XBow.png', '/img/card_ed/Princess.png', '/img/card_ed/IceWiz.png', '/img/card_ed/Fisherman.png', '/img/card_ed/eWiz.png', '/img/card_ed/InfernoD.png', '/img/card_ed/MagicArcher.png', '/img/card_ed/MotherWitch.png', '/img/card_ed/RamRider.png', '/img/card_ed/Sparky.png', '/img/card_ed/SpiritEmpress.png', '/img/card_ed/LittlePrince.png', '/img/card_ed/ArcherQueen.png', '/img/card_ed/Goblinstein.png', '/img/card_ed/Bats.png', '/img/card_ed/Minions.png', '/img/card_ed/SkellyBarrel.png', '/img/card_ed/SkeletonDragons.png', '/img/card_ed/Horde.png', '/img/card_ed/MM.png', '/img/card_ed/FlyingMachine.png', '/img/card_ed/BabyD.png', '/img/card_ed/Balloon.png', '/img/card_ed/eDragon.png', '/img/card_ed/InfernoD.png', '/img/card_ed/Phoenix.png', '/img/card_ed/SpiritEmpress.png', '/img/card_ed/Lava.png', '/img/card_ed/Skellies.png', '/img/card_ed/ElectroSpirit.png', '/img/card_ed/FireSpirit.png', '/img/card_ed/IceSpirit.png', '/img/card_ed/Gobs.png', '/img/card_ed/SpearGobs.png', '/img/card_ed/Bomber.png', '/img/card_ed/Berserker.png', '/img/card_ed/Archers.png', '/img/card_ed/Knight.png', '/img/card_ed/GobGang.png', '/img/card_ed/Firecracker.png', '/img/card_ed/RoyalDelivery.png', '/img/card_ed/Barbs.png', '/img/card_ed/Rascals.png', '/img/card_ed/RG.png', '/img/card_ed/eBarbs.png', '/img/card_ed/RoyalRecruits.png', '/img/card_ed/HealSpirit.png', '/img/card_ed/IceGolem.png', '/img/card_ed/SuspiciousBush.png', '/img/card_ed/DartGob.png', '/img/card_ed/ElixirGolem.png', '/img/card_ed/MP.png', '/img/card_ed/Musk.png', '/img/card_ed/GoblinCage.png', '/img/card_ed/Valk.png', '/img/card_ed/Ram.png', '/img/card_ed/Hog.png', '/img/card_ed/BattleHealer.png', '/img/card_ed/Furnace.png', '/img/card_ed/Zappies.png', '/img/card_ed/GoblinDemolisher.png', '/img/card_ed/Giant.png', '/img/card_ed/Wiz.png', '/img/card_ed/RoyalHogs.png', '/img/card_ed/3M.png', '/img/card_ed/BarbBarrel.png', '/img/card_ed/WallBreakers.png', '/img/card_ed/Barrel.png', '/img/card_ed/Guards.png', '/img/card_ed/Skarmy.png', '/img/card_ed/DarkPrince.png', '/img/card_ed/RuneGiant.png', '/img/card_ed/Hunter.png', '/img/card_ed/Witch.png', '/img/card_ed/Prince.png', '/img/card_ed/Bowler.png', '/img/card_ed/Exe.png', '/img/card_ed/CannonCart.png', '/img/card_ed/GiantSkelly.png', '/img/card_ed/GobGiant.png', '/img/card_ed/PEKKA.png', '/img/card_ed/ElectroGiant.png', '/img/card_ed/Golem.png', '/img/card_ed/Miner.png', '/img/card_ed/Princess.png', '/img/card_ed/IceWiz.png', '/img/card_ed/Ghost.png', '/img/card_ed/Bandit.png', '/img/card_ed/Fisherman.png', '/img/card_ed/eWiz.png', '/img/card_ed/MagicArcher.png', '/img/card_ed/Lumber.png', '/img/card_ed/NightWitch.png', '/img/card_ed/MotherWitch.png', '/img/card_ed/RamRider.png', '/img/card_ed/GoblinMachine.png', '/img/card_ed/Sparky.png', '/img/card_ed/SpiritEmpress.png', '/img/card_ed/MegaKnight.png', '/img/card_ed/LittlePrince.png', '/img/card_ed/GoldenKnight.png', '/img/card_ed/SkeletonKing.png', '/img/card_ed/MightyMiner.png', '/img/card_ed/ArcherQueen.png', '/img/card_ed/Goblinstein.png', '/img/card_ed/Monk.png', '/img/card_ed/BossBandit.png']

In [19]:
cardData ={"Card Name": [], "Card Url": []}
for i in range(len(cardName)):
        cardData["Card Name"].append(cardName[i].text.strip())
        cardData["Card Url"].append(urlsOnlyCards[i].text.strip())

AttributeError: 'str' object has no attribute 'text'

In [20]:
import requests as r
from bs4 import BeautifulSoup as bs
import pandas as pd

url = "https://www.deckshop.pro/card/list"
response = r.get(url)
soup = bs(response.text, "html.parser")

cards = soup.find_all("img", {"class": "card"})
cardData = {"Card Name": [], "Card Url": []}
for card in cards:
    name = card.get("alt")
    img_url = card.get("src")

    if name and img_url:
        cardData["Card Name"].append(name.strip())
        cardData["Card Url"].append(img_url.strip())

cardInfodf = pd.DataFrame(cardData)
cardInfodf.to_csv("ClashRoyalCards.csv", index=False)
print(cardInfodf.head())

    Card Name                        Card Url
0   Skeletons   /img/card_ed_evo/Skellies.png
1  Ice Spirit  /img/card_ed_evo/IceSpirit.png
2      Bomber     /img/card_ed_evo/Bomber.png
3        Bats       /img/card_ed_evo/Bats.png
4         Zap        /img/card_ed_evo/Zap.png

In [22]:
tableresponse = r.get("https://www.scrapethissite.com/pages/forms/")
with open("TableData.html","w") as file:
    file.write(tableresponse.text)
with open("TableData.html","r") as file:
    sourceCode = file.read()
    soup = bs(sourceCode,"html.parser")
    tableData = soup.find_all("tr")
    tableDataList = []
    for eachRow in tableData:
        cell = eachRow.find_all(["td","th"])
        singleRow=[]
        for eachCell in cell:
            singleRow.append(eachCell.get_text().strip())
        tableDataList.append(singleRow)
tableDF = pd.DataFrame(tableDataList[1:],columns=tableDataList[0])
tableDF

,Team Name,Year,Wins,Losses,OT Losses,Win %,Goals For (GF),Goals Against (GA),+ / -
0,Boston Bruins,1990,44,24,,0.55,299,264,35
1,Buffalo Sabres,1990,31,30,,0.388,292,278,14
2,Calgary Flames,1990,46,26,,0.575,344,263,81
3,Chicago Blackhawks,1990,49,23,,0.613,284,211,73
4,Detroit Red Wings,1990,34,38,,0.425,273,298,-25
5,Edmonton Oilers,1990,37,37,,0.463,272,272,0
6,Hartford Whalers,1990,31,38,,0.388,238,276,-38
7,Los Angeles Kings,1990,46,24,,0.575,340,254,86
8,Minnesota North Stars,1990,27,39,,0.338,256,266,-10
9,Montreal Canadiens,1990,39,30,,0.487,273,249,24
10,New Jersey Devils,1990,32,33,,0.4,272,264,8
11,New York Islanders,1990,25,45,,0.312,223,290,-67
12,New York Rangers,1990,36,31,,0.45,297,265,32
13,Philadelphia Flyers,1990,33,37,,0.412,252,267,-15
14,Pittsburgh Penguins,1990,41,33,,0.512,342,305,37
15,Quebec Nordiques,1990,16,50,,0.2,236,354,-118
16,St. Louis Blues,1990,47,22,,0.588,310,250,60
17,Toronto Maple Leafs,1990,23,46,,0.287,241,318,-77
18,Vancouver Canucks,1990,28,43,,0.35,243,315,-72
19,Washington Capitals,1990,37,36,,0.463,258,258,0
20,Winnipeg Jets,1990,26,43,,0.325,260,288,-28
21,Boston Bruins,1991,36,32,,0.45,270,275,-5
22,Buffalo Sabres,1991,31,37,,0.388,289,299,-10
23,Calgary Flames,1991,31,37,,0.388,296,305,-9
24,Chicago Blackhawks,1991,36,29,,0.45,257,236,21