In [2]:
# Number Addtion
import pandas as pd

def cleanPrice(listOfPrice, itemToClean):
    cleanedPrice = []
    for i in range(len(listOfPrice)):
        listOfPrice[i] = listOfPrice[i].replace(itemToClean, "")
        cleanedPrice.append(listOfPrice[i])
    return cleanedPrice

In [3]:
itemSheet = pd.read_excel("VendorProducts.xlsx",sheet_name="Items")
collectionsSheet = pd.read_excel("VendorProducts.xlsx",sheet_name="Collections")

In [4]:
itemSheet

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [5]:
collectionsSheet

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Color,Secondary Color,Size,Unit Level,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"420,000د.ع",3145891072204,82528.0,100 مل,100 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"300,000د.ع",3145891072105,82755.0,50 مل,50 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك,The Glow Stick,#F3D5C6,"19,750د.ع",7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك,The Glow Stick,#F2B2B9,"19,750د.ع",7333352079176,82571.0,25 روز جليم,25 Rose Gleam,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك,The Contour Stick,#AF8E7A,"19,750د.ع",7333352079084,82565.0,30,30,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل,Instant Anti Age Eraser Concealer 6 ml,#F5D4C5,"17,250د.ع",3600530733866,58724.0,03 معتدل,03 Fair,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"17,000د.ع",697029058770,60467.0,500 مل,500 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"6,500د.ع",697029602478,81429.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"17,000د.ع",697029041260,47028.0,500 مل,500 ml,NaN,Level1,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"6,500د.ع",697029532409,81431.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...

In [6]:
collectionsSheet.drop(columns=["Color Code","Unit Level","Is Active"],inplace=True)

In [7]:
collectionsSheet

,Item Id,Item Name,Secondary Item Name,Price,Barcode,Code,Color,Secondary Color,Size,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,"420,000د.ع",3145891072204,82528.0,100 مل,100 ml,NaN,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,"300,000د.ع",3145891072105,82755.0,50 مل,50 ml,NaN,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك,The Glow Stick,"19,750د.ع",7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,NaN,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك,The Glow Stick,"19,750د.ع",7333352079176,82571.0,25 روز جليم,25 Rose Gleam,NaN,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك,The Contour Stick,"19,750د.ع",7333352079084,82565.0,30,30,NaN,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل,Instant Anti Age Eraser Concealer 6 ml,"17,250د.ع",3600530733866,58724.0,03 معتدل,03 Fair,NaN,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,"17,000د.ع",697029058770,60467.0,500 مل,500 ml,NaN,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,"6,500د.ع",697029602478,81429.0,88.7 مل,88.7 ml,NaN,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,"17,000د.ع",697029041260,47028.0,500 مل,500 ml,NaN,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,"6,500د.ع",697029532409,81431.0,88.7 مل,88.7 ml,NaN,https://www.storeakmedia.com/storeak-erp/Store...

In [8]:
itemSheet.drop(columns=["Sub Description","Secondary Sub Description","Code"],inplace=True)

In [9]:
itemSheet

,Picture,Id,Name,Secondary Name,Barcode,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [10]:
collectionsSheet["Item Name"] = collectionsSheet["Item Name"] + " " + collectionsSheet["Color"]
collectionsSheet["Secondary Item Name"] = collectionsSheet["Secondary Item Name"] + " " + collectionsSheet["Secondary Color"]


collectionsSheet["Secondary Item Name"] = collectionsSheet["Secondary Item Name"] + " " + collectionsSheet["Secondary Color"]

In [11]:
collectionsSheet

,Item Id,Item Name,Secondary Item Name,Price,Barcode,Code,Color,Secondary Color,Size,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد 100 مل,Bleu De Chanel L'Exclusif Parfum 100 ml 100 ml,"420,000د.ع",3145891072204,82528.0,100 مل,100 ml,NaN,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد 50 مل,Bleu De Chanel L'Exclusif Parfum 50 ml 50 ml,"300,000د.ع",3145891072105,82755.0,50 مل,50 ml,NaN,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك 24 سباركلينج بيج,The Glow Stick 24 Sparkling Beige 24 Sparkling...,"19,750د.ع",7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,NaN,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك 25 روز جليم,The Glow Stick 25 Rose Gleam 25 Rose Gleam,"19,750د.ع",7333352079176,82571.0,25 روز جليم,25 Rose Gleam,NaN,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك 30,The Contour Stick 30 30,"19,750د.ع",7333352079084,82565.0,30,30,NaN,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل 03 معتدل,Instant Anti Age Eraser Concealer 6 ml 03 Fair...,"17,250د.ع",3600530733866,58724.0,03 معتدل,03 Fair,NaN,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي 500 مل,Healthy Gums Mouthwash Pure Mint 500 ml 500 ml,"17,000د.ع",697029058770,60467.0,500 مل,500 ml,NaN,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي 88.7 مل,Healthy Gums Mouthwash Pure Mint 88.7 ml 88.7 ml,"6,500د.ع",697029602478,81429.0,88.7 مل,88.7 ml,NaN,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف 500 مل,Fresh Breath Oral Rinse Mild Mint 500 ml 500 ml,"17,000د.ع",697029041260,47028.0,500 مل,500 ml,NaN,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف 88.7 مل,Fresh Breath Oral Rinse Mild Mint 88.7 ml 88.7 ml,"6,500د.ع",697029532409,81431.0,88.7 مل,88.7 ml,NaN,https://www.storeakmedia.com/storeak-erp/Store...

In [12]:
collectionsSheet.drop(columns=["Color","Secondary Color","Size"],inplace=True)
collectionsSheet.drop(columns=["Code"],inplace=True)
collectionsSheet

,Item Id,Item Name,Secondary Item Name,Price,Barcode,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد 100 مل,Bleu De Chanel L'Exclusif Parfum 100 ml 100 ml,"420,000د.ع",3145891072204,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد 50 مل,Bleu De Chanel L'Exclusif Parfum 50 ml 50 ml,"300,000د.ع",3145891072105,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك 24 سباركلينج بيج,The Glow Stick 24 Sparkling Beige 24 Sparkling...,"19,750د.ع",7333352079169,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك 25 روز جليم,The Glow Stick 25 Rose Gleam 25 Rose Gleam,"19,750د.ع",7333352079176,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك 30,The Contour Stick 30 30,"19,750د.ع",7333352079084,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل 03 معتدل,Instant Anti Age Eraser Concealer 6 ml 03 Fair...,"17,250د.ع",3600530733866,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي 500 مل,Healthy Gums Mouthwash Pure Mint 500 ml 500 ml,"17,000د.ع",697029058770,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي 88.7 مل,Healthy Gums Mouthwash Pure Mint 88.7 ml 88.7 ml,"6,500د.ع",697029602478,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف 500 مل,Fresh Breath Oral Rinse Mild Mint 500 ml 500 ml,"17,000د.ع",697029041260,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف 88.7 مل,Fresh Breath Oral Rinse Mild Mint 88.7 ml 88.7 ml,"6,500د.ع",697029532409,https://www.storeakmedia.com/storeak-erp/Store...

In [13]:
newPrice = cleanPrice(list(collectionsSheet["Price"]), ",")
newPrice = cleanPrice(newPrice,"د.ع")
collectionsSheet["Price"] = newPrice
collectionsSheet

,Item Id,Item Name,Secondary Item Name,Price,Barcode,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد 100 مل,Bleu De Chanel L'Exclusif Parfum 100 ml 100 ml,420000,3145891072204,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد 50 مل,Bleu De Chanel L'Exclusif Parfum 50 ml 50 ml,300000,3145891072105,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك 24 سباركلينج بيج,The Glow Stick 24 Sparkling Beige 24 Sparkling...,19750,7333352079169,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك 25 روز جليم,The Glow Stick 25 Rose Gleam 25 Rose Gleam,19750,7333352079176,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك 30,The Contour Stick 30 30,19750,7333352079084,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل 03 معتدل,Instant Anti Age Eraser Concealer 6 ml 03 Fair...,17250,3600530733866,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي 500 مل,Healthy Gums Mouthwash Pure Mint 500 ml 500 ml,17000,697029058770,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي 88.7 مل,Healthy Gums Mouthwash Pure Mint 88.7 ml 88.7 ml,6500,697029602478,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف 500 مل,Fresh Breath Oral Rinse Mild Mint 500 ml 500 ml,17000,697029041260,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف 88.7 مل,Fresh Breath Oral Rinse Mild Mint 88.7 ml 88.7 ml,6500,697029532409,https://www.storeakmedia.com/storeak-erp/Store...

In [14]:
itemSheet

,Picture,Id,Name,Secondary Name,Barcode,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [15]:
newPrice = cleanPrice(list(itemSheet["Price"]), ",")
newPrice = cleanPrice(newPrice,"د.ع")
itemSheet["Price"] = newPrice
itemSheet

,Picture,Id,Name,Secondary Name,Barcode,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,25000,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,30000,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,00,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,15000,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,16500,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,12000,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,10500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,15000,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,22500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [16]:
collectionsSheet

,Item Id,Item Name,Secondary Item Name,Price,Barcode,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد 100 مل,Bleu De Chanel L'Exclusif Parfum 100 ml 100 ml,420000,3145891072204,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد 50 مل,Bleu De Chanel L'Exclusif Parfum 50 ml 50 ml,300000,3145891072105,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك 24 سباركلينج بيج,The Glow Stick 24 Sparkling Beige 24 Sparkling...,19750,7333352079169,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك 25 روز جليم,The Glow Stick 25 Rose Gleam 25 Rose Gleam,19750,7333352079176,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك 30,The Contour Stick 30 30,19750,7333352079084,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل 03 معتدل,Instant Anti Age Eraser Concealer 6 ml 03 Fair...,17250,3600530733866,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي 500 مل,Healthy Gums Mouthwash Pure Mint 500 ml 500 ml,17000,697029058770,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي 88.7 مل,Healthy Gums Mouthwash Pure Mint 88.7 ml 88.7 ml,6500,697029602478,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف 500 مل,Fresh Breath Oral Rinse Mild Mint 500 ml 500 ml,17000,697029041260,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف 88.7 مل,Fresh Breath Oral Rinse Mild Mint 88.7 ml 88.7 ml,6500,697029532409,https://www.storeakmedia.com/storeak-erp/Store...

In [17]:
collectionsSheet.rename(columns={"Item Name":"Name","Secondary Item Name":"Secondary Name","Item Id":"Id",},inplace=True)

In [18]:
collectionsSheet

,Id,Name,Secondary Name,Price,Barcode,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد 100 مل,Bleu De Chanel L'Exclusif Parfum 100 ml 100 ml,420000,3145891072204,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد 50 مل,Bleu De Chanel L'Exclusif Parfum 50 ml 50 ml,300000,3145891072105,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك 24 سباركلينج بيج,The Glow Stick 24 Sparkling Beige 24 Sparkling...,19750,7333352079169,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك 25 روز جليم,The Glow Stick 25 Rose Gleam 25 Rose Gleam,19750,7333352079176,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك 30,The Contour Stick 30 30,19750,7333352079084,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل 03 معتدل,Instant Anti Age Eraser Concealer 6 ml 03 Fair...,17250,3600530733866,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي 500 مل,Healthy Gums Mouthwash Pure Mint 500 ml 500 ml,17000,697029058770,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي 88.7 مل,Healthy Gums Mouthwash Pure Mint 88.7 ml 88.7 ml,6500,697029602478,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف 500 مل,Fresh Breath Oral Rinse Mild Mint 500 ml 500 ml,17000,697029041260,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف 88.7 مل,Fresh Breath Oral Rinse Mild Mint 88.7 ml 88.7 ml,6500,697029532409,https://www.storeakmedia.com/storeak-erp/Store...

In [19]:
collectionsSheet.loc[collectionsSheet["Id"]==390187,"Secondary Name"]

0    Bleu De Chanel L'Exclusif Parfum 100 ml 100 ml
1      Bleu De Chanel L'Exclusif Parfum 50 ml 50 ml
Name: Secondary Name, dtype: str

In [20]:
for eachId in list(collectionsSheet["Id"]):
    if eachId in list(itemSheet["Id"]):
        #===============#
        Picture = collectionsSheet.loc[collectionsSheet["Id"]==eachId,"Picture"].values[0]
        Id = collectionsSheet.loc[collectionsSheet["Id"]==eachId,"Id"].values[0]
        Name = collectionsSheet.loc[collectionsSheet["Id"]==eachId,"Name"].values[0]
        SecondaryName = collectionsSheet.loc[collectionsSheet["Id"]==eachId,"Secondary Name"].values[0]
        Price = collectionsSheet.loc[collectionsSheet["Id"]==eachId,"Price"].values[0]
        mBarcode = collectionsSheet.loc[collectionsSheet["Id"]==eachId,"Barcode"].values[0]
        #===============#
        Description = itemSheet.loc[itemSheet["Id"]==eachId,"Description"].values[0]
        SecondaryDescription = itemSheet.loc[itemSheet["Id"]==eachId,"Secondary Description"].values[0]
        Menu = itemSheet.loc[itemSheet["Id"]==eachId,"Menu"].values[0]
        Brand = itemSheet.loc[itemSheet["Id"]==eachId,"Brand"].values[0]
        SecondaryBrand =itemSheet.loc[itemSheet["Id"]==eachId,"Secondary Brand"].values[0]
        HasCollection = True
        #===============#
        finaLRow = [Picture,Id,Name,SecondaryName,mBarcode,Price,Description,SecondaryDescription,Menu,Brand,SecondaryBrand,HasCollection]
        currentrowNumber = len(itemSheet["Id"])
        itemSheet.loc[currentrowNumber] = finaLRow

In [21]:
itemSheet

,Picture,Id,Name,Secondary Name,Barcode,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,25000,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,30000,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,00,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,15000,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...
39183,https://www.storeakmedia.com/storeak-erp/Store...,332027,كونسيلر فوري مضاد للشيخوخة 6 مل منير 05,Instant Anti Age Eraser Concealer 6 ml 05 Brig...,3600531396831,17250,كونسيلر مصحح بخصائص مضادة للشيخوخة تخفي علامات...,A corrective concealer with anti aging propert...,"المكياج‎ -> الوجه‎ -> كونسيلر & مصحح,المكياج‎ ...",ميبيلين,Maybelline,True
39184,https://www.storeakmedia.com/storeak-erp/Store...,316612,غسول الفم للثة الصحية بالنعناع النقي 500 مل,Healthy Gums Mouthwash Pure Mint 500 ml 500 ml,697029058770,17000,غسول الفم والاسنان لتقليل نزيف والتهابات اللثة...,Mouthwash and teeth to reduce bleeding and inf...,العناية بالبشرة‎ -> العناية بالفم‎ -> غرغرة & ...,ثيرابريث,TheraBreath,True
39185,https://www.storeakmedia.com/storeak-erp/Store...,316612,غسول الفم للثة الصحية بالنعناع النقي 500 مل,Healthy Gums Mouthwash Pure Mint 500 ml 500 ml,697029058770,17000,غسول الفم والاسنان لتقليل نزيف والتهابات اللثة...,Mouthwash and teeth to reduce bleeding and inf...,العناية بالبشرة‎ -> العناية بالفم‎ -> غرغرة & ...,ثيرابريث,TheraBreath,True
39186,NaN,316610,غسول فم منعش بالنعناع الخفيف 500 مل,Fresh Breath Oral Rinse Mild Mint 500 ml 500 ml,697029041260,17000,غسول الفم والاسنان يعمل على تحييد البكتيريا ال...,Mouthwash neutralizes sulfur producing bacteri...,العناية بالبشرة‎ -> العناية بالفم‎ -> غرغرة & ...,ذا بريث كو,The Breath.Co,True
39187,NaN,316610,غسول فم منعش بالنعناع الخفيف 500 مل,Fresh Breath Oral Rinse Mild Mint 500 ml 500 ml,697029041260,17000,غسول الفم والاسنان يعمل على تحييد البكتيريا ال...,Mouthwash neutralizes sulfur producing bacteri...,العناية بالبشرة‎ -> العناية بالفم‎ -> غرغرة & ...,ذا بريث كو,The Breath.Co,True

In [22]:
itemSheet.to_csv("FinalItemSheet.csv",index=False)