In [ ]:
# check by comparing id from boths sheets and see if all the products from
#Collections sheet exist in items sheet
# Merge both sheets
# Compare both ids = On id's getting matched retrieve the information
# For the specific product Id, Name , Secondary Name , barcode , price from collection
# for same product you can get description , secondary Description, Menu , Brand and Secondary brand from items sheet
# Attach new row at the end of items sheet

In [ ]:
import pandas as pd

In [13]:
dfItems = pd.read_excel("VendorProducts.xlsx",sheet_name="Items")
dfCollections= pd.read_excel("VendorProducts.xlsx",sheet_name="Collections")

In [14]:
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [15]:
dfCollections

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Color,Secondary Color,Size,Unit Level,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"420,000د.ع",3145891072204,82528.0,100 مل,100 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"300,000د.ع",3145891072105,82755.0,50 مل,50 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك,The Glow Stick,#F3D5C6,"19,750د.ع",7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك,The Glow Stick,#F2B2B9,"19,750د.ع",7333352079176,82571.0,25 روز جليم,25 Rose Gleam,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك,The Contour Stick,#AF8E7A,"19,750د.ع",7333352079084,82565.0,30,30,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل,Instant Anti Age Eraser Concealer 6 ml,#F5D4C5,"17,250د.ع",3600530733866,58724.0,03 معتدل,03 Fair,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"17,000د.ع",697029058770,60467.0,500 مل,500 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"6,500د.ع",697029602478,81429.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"17,000د.ع",697029041260,47028.0,500 مل,500 ml,NaN,Level1,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"6,500د.ع",697029532409,81431.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...

In [16]:
print(type(dfItems))
print(type(dfItems["Secondary Description"]))

<class 'pandas.DataFrame'>
<class 'pandas.Series'>

In [17]:
dfItems["Price"]

0         25,000د.ع
1        300,000د.ع
2         30,000د.ع
3             00د.ع
4         15,000د.ع
            ...
24697     16,500د.ع
24698     12,000د.ع
24699     10,500د.ع
24700     15,000د.ع
24701     22,500د.ع
Name: Price, Length: 24702, dtype: str

In [18]:
dfItems.info()

<class 'pandas.DataFrame'>
RangeIndex: 24702 entries, 0 to 24701
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Picture                    24300 non-null  str
 1   Id                         24702 non-null  int64
 2   Name                       24702 non-null  str
 3   Secondary Name             24702 non-null  str
 4   Barcode                    22041 non-null  str
 5   Code                       21993 non-null  str
 6   Price                      24702 non-null  str
 7   Description                24645 non-null  str
 8   Secondary Description      24644 non-null  str
 9   Sub Description            24601 non-null  str
 10  Secondary Sub Description  4 non-null      str
 11  Menu                       24699 non-null  str
 12  Brand                      24699 non-null  str
 13  Secondary Brand            24696 non-null  str
 14  Has Collections            24702 non-null  str
dtypes: int64(1), str(14)
memory usage: 2.8 MB

In [19]:
dfCollections.info()

<class 'pandas.DataFrame'>
RangeIndex: 14486 entries, 0 to 14485
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Item Id              14486 non-null  int64
 1   Item Name            14486 non-null  str
 2   Secondary Item Name  14486 non-null  str
 3   Color Code           13025 non-null  str
 4   Price                14486 non-null  str
 5   Barcode              14486 non-null  str
 6   Code                 14427 non-null  float64
 7   Color                14483 non-null  str
 8   Secondary Color      14483 non-null  str
 9   Size                 0 non-null      float64
 10  Unit Level           14486 non-null  str
 11  Is Active            14486 non-null  bool
 12  Picture              13955 non-null  str
dtypes: bool(1), float64(2), int64(1), str(9)
memory usage: 1.3 MB

In [20]:
dfItems.describe()

                  Id
count   24702.000000
mean   330583.440936
std     12701.598678
min    314991.000000
25%    321257.250000
50%    327496.500000
75%    334544.750000
max    390188.000000

In [21]:
dfItems.head()

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No

In [22]:
dfItems.tail()

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [23]:
dfItems.fillna("")

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,,,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [24]:
dfItems[["Name"]].fillna("")

                                                   Name
0                            زيت الشفاه بليجر 001، 5 مل
1                  عطر بلو دي شانيل لي اكسكلوسيف الجديد
2                 سيروم الشعر لفروة الرأس سيابوري 20 مل
3                        عطر جانيميد اودي بارفيوم 50 مل
4                   جل تصفيف الحواجب مع الببتيدات 15 مل
...                                                 ...
24697        معطر الشعر والجسم بالليمون والماتشا 150 مل
24698  معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل
24699         ماسكارا جلام اند دول تعزز نمو الرموش 8 مل
24700                        مست الجسم باشن فروت 150 مل
24701               ماسكارا فائقة الكثافة (1أسود) 15 مل

[24702 rows x 1 columns]

In [25]:
dfItems.loc(0)

In [26]:
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [27]:
dfItems[["Description","Secondary Description"]]

,Description,Secondary Description
0,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...
1,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...
2,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha..."
3,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...
4,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou..."
...,...,...
24697,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ..."
24698,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...
24699,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ..."
24700,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...
24701,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...

In [28]:
set(dfItems["Secondary Brand"])

{'4 Long Lashes',
 '7DAYS',
 'AL haramain',
 'Abdul Samad Al Qurashi',
 'Acqua Di Parisis',
 'Acqua Di Parma',
 'Agatho Perfume',
 'Agent Provocateur',
 'Al Tahara Musk',
 'Al Tahara Royal Muck',
 'Alba Botanica',
 'Albane Noble',
 'Alexandre.J',
 'Alfaparf Milano',
 'Almorel',
 'Alterna',
 'Amara Lenses',
 'Ameera London',
 'Amouage',
 'Anastasia Beverly Hills',
 'Andrea',
 'Anesthesia',
 'Anfas',
 'Angel Barlen',
 'Angel En Provence',
 'Angel Schlesser',
 'Annick Goutal',
 'Answr',
 'Antonio Croce Perfumes',
 'Anua',
 'Aquafresh',
 'Aquarelle Paris',
 'Aquarely',
 'Aramis',
 'Arcancil',
 'Ardell',
 'Argan Deluxe',
 'Arm & Hammer',
 'Armaf',
 'ArtNaturals',
 'Artdeco',
 'Ascada Beauty',
 'Aspel',
 'Assaf',
 'Ateej',
 'Atelier Des Ors',
 'Atelier Flou',
 'Atelier Versace',
 'Atyab Al Marshoud',
 'Aussie',
 'Avène',
 'Awshal Perfumes',
 'Axe',
 'Axis-y',
 'Aya',
 'Ayten',
 'Azzaro',
 'B STYLE',
 'BDK Parfums',
 'BFG',
 'BOIS 1920',
 'BaByliss',
 'Baby Foot',
 'Baby Powder',
 'Balance Cosmetics',
 'Balmy Naturel',
 'Bandido',
 'Barulab',
 'Bath & Body Works',
 'Batiste',
 'Baylis & Harding',
 'Bayt Al Saboun',
 'Be Organic',
 'Beauty Creations',
 'Beauty Formulas',
 'Beauty Legend',
 'Beauty of Joseon',
 'Bebe Perfumes',
 'Becca cosmetics',
 'Beesline',
 'Bell',
 'Benefit',
 'Bentley Perfumes',
 'Beox',
 'Bepanthen',
 'Berdoues Parfums',
 'Bere Beauty',
 'Bergamo',
 'Betres On',
 'Beurer',
 'Beyond Paradise',
 'Beyu',
 'Bic',
 'Bigen',
 'Billie Eilish',
 'Bio Beauty Pierres',
 'Bio Friendly',
 'Bio-Oil',
 'BioBalance',
 'BioBeauty',
 'Bioderma',
 'Biokap',
 'Bioliq',
 'Biore',
 'Biotulin',
 'Biovene',
 'Black Professional',
 'Bloom Dead Sea Life',
 'Boadicea the Victorious',
 'Boucheron',
 'Boulevard',
 'Bourjois',
 'Braun',
 'Briogeo',
 'Britney Spears',
 'Brut',
 'Brylcreem',
 'Burberry',
 'Bvlgari',
 'By Vilain',
 'Byphasse',
 'Byredo Parfums',
 'C.B Deodorant',
 'CHARLOTTE TILBURY',
 'Cacharel',
 'Calvin Klein',
 'Cantu',
 'Capitano',
 'Carefree',
 'Carelika',
 'Careline',
 'Carmex',
 'Carolina Herrera',
 'Cartier',
 'Castelbajac',
 'Cat Of London Lenses',
 'Cathy Doll',
 'Catrice',
 'Celia',
 'Celimax',
 'Cellbn',
 'CeraVe',
 'Cetaphil',
 'Chanel',
 'Charmacy Milano',
 'Chloe',
 'Chopard',
 'Christian Breton',
 'Christian Dior',
 'Christian Laurent',
 'Christian Louboutin',
 'Christian Provenzano',
 'Christine',
 'Chroma',
 'Clarins',
 'Clarisonic',
 'Clean & Clear',
 'Cleanic',
 'Clear',
 'Clinique',
 'Clive Christian',
 'Closeup',
 'Coach',
 'Coco Hair',
 'Coco Hair 24K',
 'Colgate',
 'Color Wow',
 'Correction',
 'Cosmaline',
 'Cosrx',
 'Costume National',
 'Cover Fx',
 'Covermark',
 'Creed',
 'Creightons',
 'Crescina',
 'Crest',
 'DAX',
 'DERMAPILL',
 'DKNY',
 'DUO Adhesives',
 'Dabur Amla',
 'Dahab Lamar Lenses',
 'Daisy Makeup',
 'Dali Beauty',
 'Dancoly',
 'David Beckham',
 'Davidoff',
 'Davini',
 'De Leon Perfumes',
 'Deborah Milano',
 'Declare',
 'Degree',
 'Delongpre',
 'Denim',
 'Dermavive',
 'Dermedic',
 'Dermolab',
 'Dermoviva',
 'Dexe',
 'Diadermine',
 'Dicora Urban Fit',
 'Diesel',
 'Difeel',
 'Disney',
 'Dolce & Gabbana',
 'Donna Karan',
 'Dove',
 'Dr. Althea',
 'Dr. Noora',
 "Dr. Scholl's",
 'Dr.Irena',
 'Dr.Jart+',
 'Dr.Jayjun',
 'Dsquared2',
 'Ducray',
 'Dunhill',
 'Dyson',
 'Déjà Vu Parfums',
 'ENZO',
 'EOS',
 'EVE',
 'Easy Beauty',
 'Ebreez Parfums',
 'Eco MAR',
 'EcoTools',
 'Eden',
 'Egyptian Magic',
 'Electimuss London',
 'Elegance',
 'Elegant Touch',
 'Elgon',
 'Elie Saab',
 'Elizabeth Arden',
 'Elizabeth Taylor',
 'Elizavecca',
 'Emanuel Ungaro',
 'Embryolisse ',
 'Emmanuelle Jane',
 'Enchanteur',
 'Eolux',
 'Eqqual Berry',
 'Ermenegildo Zegna',
 'Escada',
 'Escentric Molecules',
 'Essence',
 'Essential Parfums ',
 'Essie',
 'Estee Lauder',
 'Eternite Beauty perfect',
 'Etude ',
 'Eucerin',
 'Eunyul',
 'Euthymol',
 'Eveline',
 'EyeCandy',
 'Fair & Lovely',
 'Famous Names',
 'Farcom Professional',
 'Fem',
 'Femfresh',
 'Fendi',
 'Fenty Beauty',
 'Ferrari',
 'Fino',
 'Flex Eyes',
 'Florinda',
 'Flormar',
 "Flose'",
 'Floxia',
 'Fogg',
 'Foltene\xa0',
 'Food A Holic',
 'Footlogix',
 'Footner',
 'Foreo',
 'Forever52',
 'Fragrance Du Bois',
 'Franck Olivier',
 'Frederick Malle',
 'Freecia',
 'Freeman',
 'Fresh Look',
 'Fusswohl',
 'GISOU',
 'Gammapiu',
 'Garnier',
 'Gemology',
 'Geparlys Parfums',
 'Gerini',
 'Ghala Zayed',
 'Ghawali',
 'Gillette',
 'Gingie',
 'Giorgio Armani',
 'Gissah',
 'Givenchy',
 'Glam Glow',
 'Glazette',
 'Glossy Blossom',
 'Glow & go',
 'Glow Recipe',
 'Glycerin',
 'Glysolid',
 'Golden Rose',
 'Gosh',
 'Gothic Collection Perfumes',
 'Gucci',
 'Guerlain',
 'Guess',
 'Guy Laroche',
 'H2O1',
 'HFC',
 'Hada Labo',
 'Hadeel Alazawey',
 'Hairburst',
 'Hairotic',
 'Hayari Parfums',
 'Head & Shoulders',
 'Helios Nail',
 'Herbal Essences',
 'Herbamedicus',
 'Hermès',
 'Hi-Speedy',
 'Himalaya',
 'Huda Beauty',
 'Hugo Boss',
 'Hummer',
 'Ibraheem Al Qurashi',
 'Ikoo Infusions',
 'In Sight',
 'Inecto',
 'Inglot',
 'Initio Parfums Prives',
 'Institut Esthederm',
 'Intesa',
 'Irish Spring',
 'IsaDora',
 'Isis Pharma',
 'Issey Miyake',
 'It cosmetics',
 'Itali wax',
 'Itely Hair Fashion',
 'JB Fragrances',
 'Jacomo',
 'Jaguar',
 'Jason Wu',
 'Jean Paul Gaultier',
 'Jennifer Lopez',
 'Jergens',
 'Jeroboam',
 'Jewel',
 'Jimmy Choo',
 'Jkosmec',
 'Jo Malone London',
 'Johan.b Paris',
 'John Varvatos',
 "Johnson's",
 'Joop!',
 'Juicy Couture',
 'Junmei',
 'Just For Men',
 'Juvena',
 'K18',
 'KLAPP',
 'KUNDAL',
 'Kaaral',
 'Kajal',
 'Karen Low',
 'Kat Von D',
 'Kayali',
 'Keiko Mecheri',
 'Kemi Blending Magic',
 'Kenneth Cole',
 'Kenzo',
 'Kerastase',
 'Kevin Murphy',
 'Khatoon Beauty',
 "Kiehl's",
 'Kiko Milano',
 'Kilian',
 'Kim Kardashian',
 'Korloff Paris',
 'Korres',
 'Kylie Cosmetics',
 "L'Arc",
 "L'Artisan Parfumeur",
 "L'Orientale Fragrances",
 "L'Oréal Paris",
 "L'arvore",
 "LA'Fresh",
 'La Cresta',
 'La Roche-Posay',
 'Labello',
 'Laboratorio Olfattivo',
 'Lacoste',
 'Lador',
 'Lady Gaga',
 'Lady Speed Stick',
 'Lalique',
 'Lancaster\xa0',
 'Lancôme',
 'Laneige',
 'Lanvin',
 'Lapitak',
 'Lattafa',
 'Laura Biagiotti',
 'Laura Mercier',
 'Laurent Mazzone Parfums',
 'Laverne',
 'Le Couvent Maison de Parfum',
 'Le Falcone',
 'Lierac Paris',
 'Lionesse',
 'Lirene',
 'Listerine',
 'Locatello',
 'Loewe',
 'Lolita Bonita',
 'Lootah Perfumes',
 'Loreal Paris Professional',
 'Lost',
 'Louis Varel',
 'Louis Vuitton',
 'Lucas',
 'Luseta',
 'M.A.C',
 'M.Asam',
 'M.Micallef',
 'Magnolia',
 'Mahzen',
 'Maison Asrar',
 'Maison Crivelli',
 'Maison De Parfum',
 'Maison Francis Kurkdjian',
 'Maison Noir',
 'Maison Seed',
 'Maison Tahité',
 'Majestic',
 'Majouri',
 'Make Up For Ever',
 'Make up Factory',
 'Malizia',
 'Mancera',
 'Marc Anthony',
 'Marc Jacobs',
 'Marc Joseph',
 'Marc-Antoine Barrois Paris',
 'Marina Lashes',
 'Mario Badescu',
 'Marlies Möller',
 'Marvis',
 'Matiere Premiere',
 'Matin Martin',
 'Matrix',
 'Maui',
 'Mauresque',
 'Mavala',
 'Max Factor',
 'Max Life',
 'Maxi',
 'Maybelline',
 'Medicube',
 'Memo Paris',
 'Mercedes-Benz',
 'Merimieu',
 'Mesauda',
 'Mesauda Milano',
 'Mesauda Professional',
 'Michael Buble',
 'Michael Kors',
 'Mielle',
 'Milani',
 'Mimesis Parfums',
 'Mimosa Makeup',
 'Mina Alsheikhly',
 'Mio Skin',
 'Missha',
 'Missoni',
 'Mitchum ',
 'Miu Miu',
 'Mixsoon',
 'Mixueer',
 'Mon Reve',
 'Mont Blanc',
 'Montale Perfumes',
 'Montana Parfum',
 'Moremo',
 'Moresque',
 'Moriscent',
 'Morphe',
 'Moser',
 'Mumuso',
 'My Little Miracle',
 'Myrurgia 1916',
 'NYC',
 'NYX Professional Makeup',
 'Nabla',
 'Narciso Rodriguez',
 'Nars',
 'Nasamat',
 'Nashi',
 'Nasomatto',
 'Natural Looks',
 'Nature Republic',
 'Nawras Sattar',
 "Ne'emah",
 'Neutrogena',
 'Nimnima',
 'Nina Ricci',
 'Nishane',
 'Nitro',
 'Nivea',
 'Nobel',
 'Nobel Royale',
 'Noosoo',
 'Nora Bo Awadh',
 'Note',
 'Now',
 'OFRA Cosmetics',
 'OGX',
 'OZ Naturals',
 'Olaplex',
 'Olay',
 'Old Spice',
 'Olivia Garden',
 'On Line',
 'Oral-B',
 'Orens Parfums',
 'Orga',
 'Origins',
 'Orland Pita Play',
 'Oros',
 'Ossum',
 'Others',
 'Ouai',
 'Oud Story',
 'Pacinos',
 'Paco Rabanne',
 'Palladio',
 "Palmer's",
 'PanOxyl',
 'Panouge',
 'Pantene',
 'Parachute',
 'Parfums De Marly',
 "Parfums d'Elmar",
 'Paris Bleu',
 'Paris Hilton',
 'Paul Emilien',
 'Paul Smith',
 'Payot',
 "Penhaligon's London",
 'Perfect',
 'Perfume De Major',
 'Pernoire',
 'Perris Monte Carlo ',
 'Perry Ellis',
 'Petite Maison',
 'Pfb Vanish',
 'Ph Argan & Keratin',
 'Pharmaceris',
 'Philipp Plein ',
 'Philips',
 'Philly & Phill',
 'Phyto',
 'Pigaviva',
 'Pinky Goat',
 'Pixi Beauty',
 'Pk Pura',
 'Polso',
 'Ponds',
 'Prada',
 'Primaderm',
 'Prive Deo Spray',
 'Provoc',
 'Puccini',
 'Pupa Milano',
 'Pura Kosmetica',
 'Pure Essence Fragrance',
 'Puring',
 'Quattrolio',
 'R+Co',
 'Radha Beauty',
 'Ralph Lauren',
 'Ramla',
 'Ramon Bejar',
 'Ramon Monegal',
 'Rare Beauty ',
 'Rasasi',
 'Real Techniques',
 'Reebok',
 'Remia',
 'Remington',
 'Retrouvailles Paris',
 'Revivre',
 'Revlon',
 'Revolution',
 'Revuele',
 'Rexona',
 'Rhode ',
 'Richenna',
 'Right Guard',
 'Rimmel London',
 'Rituals',
 'Roberto Cavalli',
 'Rochas',
 'Roja ',
 'Romeo Gigli',
 'Rose Baie Paris',
 'Rosella',
 'Rosendo Mateu',
 'Royal De Maison',
 'Royal Platinume',
 'Rude Makeup',
 'SH!FTi',
 'SKIN1004',
 'SLA Paris',
 'SVR',
 'Sabalon',
 'Sally Hansen',
 'Salvador Dali',
 'Salvatore Ferragamo',
 'Sancy Paris',
 'Sanex',
 'Santoro London',
 'Sara Khatoon',
 'Savoo',
 'Schwarzkopf',
 'Sebamed',
 'Seboradin',
 'Secret',
 'Sence Beauty',
 'Sensodyne',
 'Sephora',
 'Sergio Vallanti',
 'Seventeen',
 'Shangpree',
 'Shay & Blue',
 'Shea Moisture',
 'Sheglam',
 'Shiseido',
 'Sigma Beauty',
 'Signal',
 'Signature',
 'Silvercrest',
 'Simple',
 'Sisley Paris',
 'Sistelle Paris',
 'Skala',
 'Skin Proud',
 'Skincode',
 'Skinlab',
 'Slazenger',
 'Smashbox',
 'Soft Foot',
 'Soft Skin',
 'Sol De Janeiro',
 'Solfege Collection',
 'Some By Mi',
 'Soskin',
 'Sosoim',
 'Sospiro',
 'Speed Stick',
 'Spider Man',
 'Spirit Of Kings',
 'St.Ives',
 'Stamp',
 'Star Wars',
 'Stellary',
 'Steve Martin Paris',
 'Sturgeon',
 'Suave',
 'Subrina',
 'Sugar Bear Hair',
 'Summer Fridays',
 "Summer's Eve",
 'Sunny Isle',
 'Swiss Image',
 'Syoss',
 'TOCOBO',
 "TRESemme'",
 'TUMI',
 'Tabac Original',
 'Tailaimei',
 'Tarte',
 'Tea Tree',
 'Teba Khalil',
 'Ted Baker',
 'Ted Lapidus Parfume',
 'Teotema',
 'Thayers',
 'The Balm',
 'The Body Shop',
 'The Breath.Co',
 'The Fragrance Kitchen',
 'The House Of Oud',
 'The Inkey List',
 'The Ordinary',
 'The Palace Of Perfumes',
 'The Purest Solutions',
 'The Scent',
 'The Secret Frankincense',
 'The Woods Collection',
 'TheraBreath',
 'Thierry Mugler',
 'Thomas Kosmala',
 'Tiamo',
 'Titania',
 'Tiziana Terenzi',
 'Tizo',
 'Tom Ford',
 'Tonymoly',
 'Too Faced',
 'Top Notch',
 'Tory Burch',
 'Trim',
 'Trussardi',
 'Tsubaki',
 'Turquaz',
 'Twisted Sista',
 'U.B.U',
 'Ulric de Varens',
 'Ultra',
 'Under Twenty',
 "Unique'e Luxury",
 'Urban Decay',
 'V Canto',
 'VIVIAN GRAY',
 'Valentino',
 'Van Cleef & Arpels',
 'Vaseline',
 'Veet',
 'Vegan',
 'Vejetree',
 'Venuse',
 'Versace',
 'Versailles Beauté',
 'Vertus Paris',
 'Vichy',
 "Victoria's Secret",
 'Victorinox ',
 'Viktor & Rolf',
 'Vitadea',
 'Viva',
 'Vogue',
 'Voilier',
 'Voox',
 'Voyage',
 'Western Valley',
 'Wet N Wild',
 'White Glo',
 'Widian Arabia',
 'Wild Science Lab',
 'Wisdom',
 "Women'Secret",
 'Xerjoff',
 'YNM',
 'Yougee',
 'Youmi Beauty',
 'Yucca',
 'Yves De Sistelle',
 'Yves Rocher',
 'Yves Saint Laurent',
 'ZK Beauty',
 'Zeena',
 'bye bye blemish',
 'dr.Clinic',
 'e.l.f.',
 'ego QV',
 'katrina',
 'kirkland signature',
 'lux',
 nan,
 'oman luxury',
 'purederm',
 'sheikha',
 'so...?'}

In [29]:
dfItems[dfItems["Secondary Brand"]=="Nivea"]

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
15,NaN,390143,جل استحمام بزيت جوز الهند والجوجوبا 750 مل,Coconut & Jojoba Oil shower gel 750 ml,4005900998811,NaN,"8,000د.ع",جل استحمام بزيت جوز الهند والجوجوبا يمنحكِ بشر...,Shower gel with coconut and jojoba oil gives y...,|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
809,https://www.storeakmedia.com/storeak-erp/Store...,359629,بلسم ما بعد الحلاقة للبشرة الحساسة برو ألترا ك...,After Shave Balm Sensitive Pro Ultra Calming 1...,9005800347479,0,"9,000د.ع",بلسم مهدئ البشرة ما بعد الحلاقة، تحتوي تركيبته...,"This soothing aftershave balm, formulated with...",|نيفيا|Nivea|العناية بالرجال بعد الحلاقة|Men C...,NaN,العناية بالرجال‎ -> اللحية‎ -> بعد الحلاقة,نيفيا,Nivea,No
810,https://www.storeakmedia.com/storeak-erp/Store...,359628,جل الاستحمام كريم كير750 مل,Shower Gel Creme Care 750 ml,4006000095752,0,"8,000د.ع",غسول الجسم ينظف بشرتكِ بلطف أثناء الاستحمام، ب...,This body wash gently cleanses your skin while...,|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
814,https://www.storeakmedia.com/storeak-erp/Store...,359607,جل استحمام كريم سموث 750 مل,Shower Gel Cream Smooth 750 ml,4006000095738,0,"8,000د.ع",جل استحمام يمنحك بشرة نظيفة وناعمة وصحية بشكل ...,"Shower gel that gives you naturally clean, sof...",|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
815,https://www.storeakmedia.com/storeak-erp/Store...,359606,جل استحمام كريم سوفت 750 مل,Shower Gel Creme Soft 750 ml,4006000095776,0,"8,000د.ع",جل استحمام يمنحك بشرة نظيفة وناعمة وصحية بشكل ...,"Shower gel that gives you naturally clean, sof...",|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22999,https://www.storeakmedia.com/storeak-erp/Store...,316752,رغوة حلاقة منعشة للبشرة الحساسة 200 مل,Sensitive Cooling Shaving Foam 200 ml,4005900378255,0,"6,000د.ع","رغوة الحلاقة للرجال, تعمل على تنعيم اللحية لحل...",Men's Shaving Foam Softens the beard for a clo...,|نيفيا|Nivea|العناية بالرجال جل ورغوة الحلاقة|...,NaN,العناية بالرجال‎ -> اللحية‎ -> جل & رغوة الحلاقة,نيفيا,Nivea,No
23063,https://www.storeakmedia.com/storeak-erp/Store...,316688,غسول التنظيف العميق للوجه واللحية 100 مل,Deep Face & Beard Wash Cleanser 100 ml,4005900517951,0,"7,750د.ع","غسول الوجه للرجال, تركيبة مبتكرة بالفحم الأسود...","Face wash for men, an innovative formula with ...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No
23064,https://www.storeakmedia.com/storeak-erp/Store...,316687,غسول منعش للوجه 100 مل,Refreshing Face Wash 100 ml,4005808228010,0,"7,250د.ع","غسول الوجه للرجال, يزيل الأوساخ والزيوت الزائد...","Face wash for men, removes dirt and excess oil...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No
23065,https://www.storeakmedia.com/storeak-erp/Store...,316686,مقشر الوجه ديب بقوة الكاربون 75 مل,Deep Black Carbon Face Scrub 75 ml,4005900678522,0,"7,750د.ع","مقشر الوجه للرجال, بتركيبة الفحم الأسود التي ت...","Facial scrub for men, with a black carbon form...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No
23066,https://www.storeakmedia.com/storeak-erp/Store...,316685,غسول الوجه ديب لازالة الحبوب وزيوت البشرة 100 مل,Deep Pimple & Oil Clear Face Wash 100 ml,4005900818119,0,"8,500د.ع","غسول الوجه للرجال, يقوم بتنظيف وتنقية البشرة ب...","Facial wash for men, it gently cleanses and pu...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No

In [35]:
MessyPrice =  list(dfItems["Price"])
CleanedPrice = []
for price in MessyPrice:
   price = price.replace("د.ع","")
   price = price.replace(",","")
   CleanedPrice.append(int(price))
dfItems["Price"]=CleanedPrice

AttributeError: 'int' object has no attribute 'replace'

In [36]:
CleanedPrice

[]

In [37]:
dfItems["Price"]

0         25000
1        300000
2         30000
3             0
4         15000
          ...
24697     16500
24698     12000
24699     10500
24700     15000
24701     22500
Name: Price, Length: 24702, dtype: int64

In [39]:
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,25000,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,30000,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,0,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,15000,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,16500,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,12000,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,10500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,15000,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,22500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [40]:
dfItems[(dfItems["Secondary Brand"]=="Nivea") & (dfItems["Price"]>1000)]

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
15,NaN,390143,جل استحمام بزيت جوز الهند والجوجوبا 750 مل,Coconut & Jojoba Oil shower gel 750 ml,4005900998811,NaN,8000,جل استحمام بزيت جوز الهند والجوجوبا يمنحكِ بشر...,Shower gel with coconut and jojoba oil gives y...,|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
809,https://www.storeakmedia.com/storeak-erp/Store...,359629,بلسم ما بعد الحلاقة للبشرة الحساسة برو ألترا ك...,After Shave Balm Sensitive Pro Ultra Calming 1...,9005800347479,0,9000,بلسم مهدئ البشرة ما بعد الحلاقة، تحتوي تركيبته...,"This soothing aftershave balm, formulated with...",|نيفيا|Nivea|العناية بالرجال بعد الحلاقة|Men C...,NaN,العناية بالرجال‎ -> اللحية‎ -> بعد الحلاقة,نيفيا,Nivea,No
810,https://www.storeakmedia.com/storeak-erp/Store...,359628,جل الاستحمام كريم كير750 مل,Shower Gel Creme Care 750 ml,4006000095752,0,8000,غسول الجسم ينظف بشرتكِ بلطف أثناء الاستحمام، ب...,This body wash gently cleanses your skin while...,|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
814,https://www.storeakmedia.com/storeak-erp/Store...,359607,جل استحمام كريم سموث 750 مل,Shower Gel Cream Smooth 750 ml,4006000095738,0,8000,جل استحمام يمنحك بشرة نظيفة وناعمة وصحية بشكل ...,"Shower gel that gives you naturally clean, sof...",|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
815,https://www.storeakmedia.com/storeak-erp/Store...,359606,جل استحمام كريم سوفت 750 مل,Shower Gel Creme Soft 750 ml,4006000095776,0,8000,جل استحمام يمنحك بشرة نظيفة وناعمة وصحية بشكل ...,"Shower gel that gives you naturally clean, sof...",|نيفيا|Nivea|العناية بالجسم غسول الجسم|Body Ca...,NaN,العناية بالجسم‎ -> غسول الجسم,نيفيا,Nivea,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22999,https://www.storeakmedia.com/storeak-erp/Store...,316752,رغوة حلاقة منعشة للبشرة الحساسة 200 مل,Sensitive Cooling Shaving Foam 200 ml,4005900378255,0,6000,"رغوة الحلاقة للرجال, تعمل على تنعيم اللحية لحل...",Men's Shaving Foam Softens the beard for a clo...,|نيفيا|Nivea|العناية بالرجال جل ورغوة الحلاقة|...,NaN,العناية بالرجال‎ -> اللحية‎ -> جل & رغوة الحلاقة,نيفيا,Nivea,No
23063,https://www.storeakmedia.com/storeak-erp/Store...,316688,غسول التنظيف العميق للوجه واللحية 100 مل,Deep Face & Beard Wash Cleanser 100 ml,4005900517951,0,7750,"غسول الوجه للرجال, تركيبة مبتكرة بالفحم الأسود...","Face wash for men, an innovative formula with ...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No
23064,https://www.storeakmedia.com/storeak-erp/Store...,316687,غسول منعش للوجه 100 مل,Refreshing Face Wash 100 ml,4005808228010,0,7250,"غسول الوجه للرجال, يزيل الأوساخ والزيوت الزائد...","Face wash for men, removes dirt and excess oil...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No
23065,https://www.storeakmedia.com/storeak-erp/Store...,316686,مقشر الوجه ديب بقوة الكاربون 75 مل,Deep Black Carbon Face Scrub 75 ml,4005900678522,0,7750,"مقشر الوجه للرجال, بتركيبة الفحم الأسود التي ت...","Facial scrub for men, with a black carbon form...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No
23066,https://www.storeakmedia.com/storeak-erp/Store...,316685,غسول الوجه ديب لازالة الحبوب وزيوت البشرة 100 مل,Deep Pimple & Oil Clear Face Wash 100 ml,4005900818119,0,8500,"غسول الوجه للرجال, يقوم بتنظيف وتنقية البشرة ب...","Facial wash for men, it gently cleanses and pu...",|نيفيا|Nivea|العناية بالرجال منظف الوجه|Men Ca...,NaN,العناية بالرجال‎ -> الوجه‎ -> منظف الوجه,نيفيا,Nivea,No

In [41]:
dfItems.loc[dfItems["Id"]==359629,"Price"]=15000

In [42]:
dfItems[dfItems["Id"]==359629]

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
809,https://www.storeakmedia.com/storeak-erp/Store...,359629,بلسم ما بعد الحلاقة للبشرة الحساسة برو ألترا ك...,After Shave Balm Sensitive Pro Ultra Calming 1...,9005800347479,0,15000,بلسم مهدئ البشرة ما بعد الحلاقة، تحتوي تركيبته...,"This soothing aftershave balm, formulated with...",|نيفيا|Nivea|العناية بالرجال بعد الحلاقة|Men C...,NaN,العناية بالرجال‎ -> اللحية‎ -> بعد الحلاقة,نيفيا,Nivea,No

In [43]:
dfItems[["Secondary Name", "Price"]]

                                          Secondary Name   Price
0                             Pleasure Lip Oil 001, 5 ml   25000
1                       Bleu De Chanel L'Exclusif Parfum  300000
2                        Seapuri Scalpy Hair Serum 20 ml   30000
3                                     Ganymede EDP 50 ml       0
4                  Brow Styling Gel With Peptides 15 ml    15000
...                                                  ...     ...
24697              Lime & Matcha Hair & Body Mist 150 ml   16500
24698       Pink Pepper & Lychee Hair & Body Mist 150 ml   12000
24699  Glam & Doll Boost Lash Growth Volume Mascara 8 ml   10500
24700                      Body Mist Passion Fruit150 ml   15000
24701              Volume Supreme Mascara (1Black) 15 ml   22500

[24702 rows x 2 columns]

In [44]:
dfItems["New Secondary Name"] = dfItems["Secondary Name"].str.cat(dfItems['Price'].astype(str),sep="")
dfItems[["Secondary Name","New Secondary Name"]]

,Secondary Name,New Secondary Name
0,"Pleasure Lip Oil 001, 5 ml","Pleasure Lip Oil 001, 5 ml25000"
1,Bleu De Chanel L'Exclusif Parfum,Bleu De Chanel L'Exclusif Parfum300000
2,Seapuri Scalpy Hair Serum 20 ml,Seapuri Scalpy Hair Serum 20 ml30000
3,Ganymede EDP 50 ml,Ganymede EDP 50 ml0
4,Brow Styling Gel With Peptides 15 ml,Brow Styling Gel With Peptides 15 ml 15000
...,...,...
24697,Lime & Matcha Hair & Body Mist 150 ml,Lime & Matcha Hair & Body Mist 150 ml16500
24698,Pink Pepper & Lychee Hair & Body Mist 150 ml,Pink Pepper & Lychee Hair & Body Mist 150 ml12000
24699,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,Glam & Doll Boost Lash Growth Volume Mascara 8...
24700,Body Mist Passion Fruit150 ml,Body Mist Passion Fruit150 ml15000
24701,Volume Supreme Mascara (1Black) 15 ml,Volume Supreme Mascara (1Black) 15 ml22500

In [45]:
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections,New Secondary Name
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,25000,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No,"Pleasure Lip Oil 001, 5 ml25000"
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes,Bleu De Chanel L'Exclusif Parfum300000
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,30000,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No,Seapuri Scalpy Hair Serum 20 ml30000
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,0,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No,Ganymede EDP 50 ml0
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,15000,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No,Brow Styling Gel With Peptides 15 ml 15000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,16500,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No,Lime & Matcha Hair & Body Mist 150 ml16500
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,12000,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No,Pink Pepper & Lychee Hair & Body Mist 150 ml12000
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,10500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No,Glam & Doll Boost Lash Growth Volume Mascara 8...
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,15000,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No,Body Mist Passion Fruit150 ml15000
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,22500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No,Volume Supreme Mascara (1Black) 15 ml22500

In [46]:
dfItems.drop(columns=["Sub Description","Secondary Sub Description"],inplace=True)

In [47]:
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections,New Secondary Name
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,25000,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No,"Pleasure Lip Oil 001, 5 ml25000"
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes,Bleu De Chanel L'Exclusif Parfum300000
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,30000,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No,Seapuri Scalpy Hair Serum 20 ml30000
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,0,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No,Ganymede EDP 50 ml0
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,15000,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No,Brow Styling Gel With Peptides 15 ml 15000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,16500,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No,Lime & Matcha Hair & Body Mist 150 ml16500
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,12000,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No,Pink Pepper & Lychee Hair & Body Mist 150 ml12000
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,10500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No,Glam & Doll Boost Lash Growth Volume Mascara 8...
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,15000,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No,Body Mist Passion Fruit150 ml15000
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,22500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No,Volume Supreme Mascara (1Black) 15 ml22500

In [48]:
dfItems.rename(columns={"English Name":"English Names","Name":"Arabic Names"},inplace=True)
dfItems

,Picture,Id,Arabic Names,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections,New Secondary Name
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,25000,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No,"Pleasure Lip Oil 001, 5 ml25000"
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes,Bleu De Chanel L'Exclusif Parfum300000
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,30000,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No,Seapuri Scalpy Hair Serum 20 ml30000
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,0,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No,Ganymede EDP 50 ml0
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,15000,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No,Brow Styling Gel With Peptides 15 ml 15000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,16500,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No,Lime & Matcha Hair & Body Mist 150 ml16500
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,12000,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No,Pink Pepper & Lychee Hair & Body Mist 150 ml12000
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,10500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No,Glam & Doll Boost Lash Growth Volume Mascara 8...
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,15000,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No,Body Mist Passion Fruit150 ml15000
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,22500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No,Volume Supreme Mascara (1Black) 15 ml22500

In [49]:
dfCollections
# Drop columns size, Unit level
# Clean Price column
# Concatenate Item name with color & Secondary Item Name with Secondary Color
# Assign to the same columns

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Color,Secondary Color,Size,Unit Level,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"420,000د.ع",3145891072204,82528.0,100 مل,100 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"300,000د.ع",3145891072105,82755.0,50 مل,50 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك,The Glow Stick,#F3D5C6,"19,750د.ع",7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك,The Glow Stick,#F2B2B9,"19,750د.ع",7333352079176,82571.0,25 روز جليم,25 Rose Gleam,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك,The Contour Stick,#AF8E7A,"19,750د.ع",7333352079084,82565.0,30,30,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل,Instant Anti Age Eraser Concealer 6 ml,#F5D4C5,"17,250د.ع",3600530733866,58724.0,03 معتدل,03 Fair,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"17,000د.ع",697029058770,60467.0,500 مل,500 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"6,500د.ع",697029602478,81429.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"17,000د.ع",697029041260,47028.0,500 مل,500 ml,NaN,Level1,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"6,500د.ع",697029532409,81431.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...

In [50]:
dfCollections.drop(columns=["Size","Unit Level"],inplace=True)

In [51]:
dfCollections

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Color,Secondary Color,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"420,000د.ع",3145891072204,82528.0,100 مل,100 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"300,000د.ع",3145891072105,82755.0,50 مل,50 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك,The Glow Stick,#F3D5C6,"19,750د.ع",7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك,The Glow Stick,#F2B2B9,"19,750د.ع",7333352079176,82571.0,25 روز جليم,25 Rose Gleam,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك,The Contour Stick,#AF8E7A,"19,750د.ع",7333352079084,82565.0,30,30,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل,Instant Anti Age Eraser Concealer 6 ml,#F5D4C5,"17,250د.ع",3600530733866,58724.0,03 معتدل,03 Fair,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"17,000د.ع",697029058770,60467.0,500 مل,500 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"6,500د.ع",697029602478,81429.0,88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"17,000د.ع",697029041260,47028.0,500 مل,500 ml,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"6,500د.ع",697029532409,81431.0,88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...

In [52]:
MessyPrice =  list(dfCollections["Price"])
CleanedPrice = []
for price in MessyPrice:
   price = price.replace("د.ع","")
   price = price.replace(",","")
   CleanedPrice.append(int(price))
dfCollections["Price"]=CleanedPrice

In [53]:
dfCollections

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Color,Secondary Color,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,420000,3145891072204,82528.0,100 مل,100 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,300000,3145891072105,82755.0,50 مل,50 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك,The Glow Stick,#F3D5C6,19750,7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك,The Glow Stick,#F2B2B9,19750,7333352079176,82571.0,25 روز جليم,25 Rose Gleam,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك,The Contour Stick,#AF8E7A,19750,7333352079084,82565.0,30,30,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل,Instant Anti Age Eraser Concealer 6 ml,#F5D4C5,17250,3600530733866,58724.0,03 معتدل,03 Fair,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,17000,697029058770,60467.0,500 مل,500 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,6500,697029602478,81429.0,88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,17000,697029041260,47028.0,500 مل,500 ml,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,6500,697029532409,81431.0,88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...

In [54]:
dfCollections["Item Name"] = dfCollections["Item Name"].str.cat(dfCollections['Color'].astype(str),sep="")
dfCollections

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Color,Secondary Color,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد100 مل,Bleu De Chanel L'Exclusif Parfum,NaN,420000,3145891072204,82528.0,100 مل,100 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد50 مل,Bleu De Chanel L'Exclusif Parfum,NaN,300000,3145891072105,82755.0,50 مل,50 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك24 سباركلينج بيج,The Glow Stick,#F3D5C6,19750,7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك25 روز جليم,The Glow Stick,#F2B2B9,19750,7333352079176,82571.0,25 روز جليم,25 Rose Gleam,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك30,The Contour Stick,#AF8E7A,19750,7333352079084,82565.0,30,30,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل03 معتدل,Instant Anti Age Eraser Concealer 6 ml,#F5D4C5,17250,3600530733866,58724.0,03 معتدل,03 Fair,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي500 مل,Healthy Gums Mouthwash Pure Mint,NaN,17000,697029058770,60467.0,500 مل,500 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي88.7 مل,Healthy Gums Mouthwash Pure Mint,NaN,6500,697029602478,81429.0,88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف500 مل,Fresh Breath Oral Rinse Mild Mint,NaN,17000,697029041260,47028.0,500 مل,500 ml,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف88.7 مل,Fresh Breath Oral Rinse Mild Mint,NaN,6500,697029532409,81431.0,88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...

In [55]:
dfCollections["Secondary Item Name"] = dfCollections["Secondary Item Name"].str.cat(dfCollections['Secondary Color'].astype(str),sep="")
dfCollections

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Color,Secondary Color,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد100 مل,Bleu De Chanel L'Exclusif Parfum100 ml,NaN,420000,3145891072204,82528.0,100 مل,100 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد50 مل,Bleu De Chanel L'Exclusif Parfum50 ml,NaN,300000,3145891072105,82755.0,50 مل,50 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك24 سباركلينج بيج,The Glow Stick24 Sparkling Beige,#F3D5C6,19750,7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك25 روز جليم,The Glow Stick25 Rose Gleam,#F2B2B9,19750,7333352079176,82571.0,25 روز جليم,25 Rose Gleam,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك30,The Contour Stick30,#AF8E7A,19750,7333352079084,82565.0,30,30,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل03 معتدل,Instant Anti Age Eraser Concealer 6 ml03 Fair,#F5D4C5,17250,3600530733866,58724.0,03 معتدل,03 Fair,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي500 مل,Healthy Gums Mouthwash Pure Mint500 ml,NaN,17000,697029058770,60467.0,500 مل,500 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي88.7 مل,Healthy Gums Mouthwash Pure Mint88.7 ml,NaN,6500,697029602478,81429.0,88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف500 مل,Fresh Breath Oral Rinse Mild Mint500 ml,NaN,17000,697029041260,47028.0,500 مل,500 ml,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف88.7 مل,Fresh Breath Oral Rinse Mild Mint88.7 ml,NaN,6500,697029532409,81431.0,88.7 مل,88.7 ml,True,https://www.storeakmedia.com/storeak-erp/Store...

In [56]:
dfCollections.drop(columns=["Color","Secondary Color"],inplace=True)
dfCollections

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد100 مل,Bleu De Chanel L'Exclusif Parfum100 ml,NaN,420000,3145891072204,82528.0,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد50 مل,Bleu De Chanel L'Exclusif Parfum50 ml,NaN,300000,3145891072105,82755.0,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك24 سباركلينج بيج,The Glow Stick24 Sparkling Beige,#F3D5C6,19750,7333352079169,82570.0,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك25 روز جليم,The Glow Stick25 Rose Gleam,#F2B2B9,19750,7333352079176,82571.0,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك30,The Contour Stick30,#AF8E7A,19750,7333352079084,82565.0,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل03 معتدل,Instant Anti Age Eraser Concealer 6 ml03 Fair,#F5D4C5,17250,3600530733866,58724.0,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي500 مل,Healthy Gums Mouthwash Pure Mint500 ml,NaN,17000,697029058770,60467.0,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي88.7 مل,Healthy Gums Mouthwash Pure Mint88.7 ml,NaN,6500,697029602478,81429.0,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف500 مل,Fresh Breath Oral Rinse Mild Mint500 ml,NaN,17000,697029041260,47028.0,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف88.7 مل,Fresh Breath Oral Rinse Mild Mint88.7 ml,NaN,6500,697029532409,81431.0,True,https://www.storeakmedia.com/storeak-erp/Store...

In [57]:
dfItems

,Picture,Id,Arabic Names,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections,New Secondary Name
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,25000,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No,"Pleasure Lip Oil 001, 5 ml25000"
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes,Bleu De Chanel L'Exclusif Parfum300000
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,30000,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No,Seapuri Scalpy Hair Serum 20 ml30000
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,0,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No,Ganymede EDP 50 ml0
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,15000,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No,Brow Styling Gel With Peptides 15 ml 15000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,16500,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No,Lime & Matcha Hair & Body Mist 150 ml16500
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,12000,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No,Pink Pepper & Lychee Hair & Body Mist 150 ml12000
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,10500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No,Glam & Doll Boost Lash Growth Volume Mascara 8...
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,15000,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No,Body Mist Passion Fruit150 ml15000
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,22500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No,Volume Supreme Mascara (1Black) 15 ml22500

In [58]:
dfItems.drop(columns=["Sub Description","Secondary Sub Description"],inplace=True)
dfItems

KeyError: "['Sub Description', 'Secondary Sub Description'] not found in axis"

In [59]:
MessyPrice =  list(dfItems["Price"])
CleanedPrice = []
for price in MessyPrice:
   price = price.replace("د.ع","")
   price = price.replace(",","")
   CleanedPrice.append(int(price))
dfItems["Price"]=CleanedPrice

AttributeError: 'int' object has no attribute 'replace'

In [60]:
dfItems

,Picture,Id,Arabic Names,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections,New Secondary Name
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,25000,"زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No,"Pleasure Lip Oil 001, 5 ml25000"
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes,Bleu De Chanel L'Exclusif Parfum300000
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,30000,سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No,Seapuri Scalpy Hair Serum 20 ml30000
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,0,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No,Ganymede EDP 50 ml0
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,15000,امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No,Brow Styling Gel With Peptides 15 ml 15000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,16500,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No,Lime & Matcha Hair & Body Mist 150 ml16500
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,12000,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No,Pink Pepper & Lychee Hair & Body Mist 150 ml12000
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,10500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No,Glam & Doll Boost Lash Growth Volume Mascara 8...
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,15000,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No,Body Mist Passion Fruit150 ml15000
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,22500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No,Volume Supreme Mascara (1Black) 15 ml22500

In [61]:
dfItems[dfItems["Has Collections"]=="Yes"]

,Picture,Id,Arabic Names,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Menu,Brand,Secondary Brand,Has Collections,New Secondary Name
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,300000,عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes,Bleu De Chanel L'Exclusif Parfum300000
60,https://www.storeakmedia.com/storeak-erp/Store...,364804,هايلايتر ستك,The Glow Stick,NaN,NaN,19750,هايلايتر بتركيبة كريمية خفيفة الوزن تنير البشر...,"A lightweight, creamy highlighter that instant...",المكياج‎ -> الخدود‎ -> اضاءة‎ -> ستك,إيزادورا,IsaDora,Yes,The Glow Stick19750
61,https://www.storeakmedia.com/storeak-erp/Store...,364793,كونتور ستك,The Contour Stick,NaN,NaN,19750,كونتور يتميز بتركيبة كريمية ناعمة سهلة الدمج م...,"Contour features a soft, creamy formula that b...",المكياج‎ -> الوجه‎ -> كونتور,إيزادورا,IsaDora,Yes,The Contour Stick19750
94,https://www.storeakmedia.com/storeak-erp/Store...,364529,كريم أساس سائل ميكس جلو تينت إسنس,Liquid Foundation Healthy Mix Glow Tint Essence,NaN,NaN,28750,كريم اساس يتميز بتركيبة مبتكرة تجمع بين العناي...,A foundation with an innovative formula that c...,المكياج‎ -> الوجه‎ -> كريم أساس‎ -> جميع انواع...,برجواز,Bourjois,Yes,Liquid Foundation Healthy Mix Glow Tint Essenc...
107,https://www.storeakmedia.com/storeak-erp/Store...,364479,كريم أساس فوندوتينتا وندر مي ديفندر بعامل حماي...,Fondotinta Wonder Me Defender SPF 50,NaN,NaN,35000,كريم أساس مقاوم للماء والرطوبة، يوفر تغطية قاب...,"A water resistant, humidity resistant foundati...",المكياج‎ -> الوجه‎ -> كريم أساس‎ -> جميع انواع...,بوبا ميلانو,Pupa Milano,Yes,Fondotinta Wonder Me Defender SPF 5035000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8252,https://www.storeakmedia.com/storeak-erp/Store...,332030,كونسيلر دريم لومي تاتش,Dream Lumi Touch Concealer,NaN,NaN,6250,كونسيلر سائل يمتاز بتركيبة ناعمة تضيء وتغطي ال...,A liquid concealer with a smooth texture that ...,"المكياج‎ -> الوجه‎ -> كونسيلر & مصحح,المكياج‎ ...",ميبيلين,Maybelline,Yes,Dream Lumi Touch Concealer6250
8253,https://www.storeakmedia.com/storeak-erp/Store...,332028,كريم أساس سائل دريم ساتين 30 مل,Dream Satin Liquid Foundation 30 ml,NaN,NaN,21750,كريم اساس يتميز بتركيبة سائلة مع خصائص ترطيب ل...,Foundation that is characterized by a liquid f...,المكياج‎ -> الوجه‎ -> كريم أساس‎ -> جميع انواع...,ميبيلين,Maybelline,Yes,Dream Satin Liquid Foundation 30 ml21750
8254,https://www.storeakmedia.com/storeak-erp/Store...,332027,كونسيلر فوري مضاد للشيخوخة 6 مل,Instant Anti Age Eraser Concealer 6 ml,NaN,NaN,17250,كونسيلر مصحح بخصائص مضادة للشيخوخة تخفي علامات...,A corrective concealer with anti aging propert...,"المكياج‎ -> الوجه‎ -> كونسيلر & مصحح,المكياج‎ ...",ميبيلين,Maybelline,Yes,Instant Anti Age Eraser Concealer 6 ml17250
23139,https://www.storeakmedia.com/storeak-erp/Store...,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,C - 3,6500,غسول الفم والاسنان لتقليل نزيف والتهابات اللثة...,Mouthwash and teeth to reduce bleeding and inf...,العناية بالبشرة‎ -> العناية بالفم‎ -> غرغرة & ...,ثيرابريث,TheraBreath,Yes,Healthy Gums Mouthwash Pure Mint6500
23141,https://www.storeakmedia.com/storeak-erp/Store...,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,D - 4,6500,غسول الفم والاسنان يعمل على تحييد البكتيريا ال...,Mouthwash neutralizes sulfur producing bacteri...,العناية بالبشرة‎ -> العناية بالفم‎ -> غرغرة & ...,ذا بريث كو,The Breath.Co,Yes,Fresh Breath Oral Rinse Mild Mint6500

In [62]:
dfCollections

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد100 مل,Bleu De Chanel L'Exclusif Parfum100 ml,NaN,420000,3145891072204,82528.0,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد50 مل,Bleu De Chanel L'Exclusif Parfum50 ml,NaN,300000,3145891072105,82755.0,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك24 سباركلينج بيج,The Glow Stick24 Sparkling Beige,#F3D5C6,19750,7333352079169,82570.0,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك25 روز جليم,The Glow Stick25 Rose Gleam,#F2B2B9,19750,7333352079176,82571.0,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك30,The Contour Stick30,#AF8E7A,19750,7333352079084,82565.0,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل03 معتدل,Instant Anti Age Eraser Concealer 6 ml03 Fair,#F5D4C5,17250,3600530733866,58724.0,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي500 مل,Healthy Gums Mouthwash Pure Mint500 ml,NaN,17000,697029058770,60467.0,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي88.7 مل,Healthy Gums Mouthwash Pure Mint88.7 ml,NaN,6500,697029602478,81429.0,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف500 مل,Fresh Breath Oral Rinse Mild Mint500 ml,NaN,17000,697029041260,47028.0,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف88.7 مل,Fresh Breath Oral Rinse Mild Mint88.7 ml,NaN,6500,697029532409,81431.0,True,https://www.storeakmedia.com/storeak-erp/Store...

In [ ]:
# check by comparing id from boths sheets and see if all the products from
#Collections sheet exist in items sheet
# Merge both sheets
# Compare both ids = On id's getting matched retrieve the information
# For the specific product Id, Name , Secondary Name , barcode , price from collection
# for same product you can get description , secondary Description, Menu , Brand and Secondary brand from items sheet
# Attach new row at the end of items sheet

In [63]:
file = "VendorProducts.xlsx"

In [64]:
dfItems = pd.read_excel(file,sheet_name="Items")
dfCollections = pd.read_excel(file,sheet_name="Collections")

In [65]:
matchIds = dfCollections["Item Id"].isin(dfItems["Id"])

In [66]:
existsIds = matchIds.all()

In [68]:
if existsIds:
    print("All collection sheet Item id exist in the Items id Sheet.")
else:
    missing_products = dfCollections[~matchIds]
    print(f"Missing products found: {len(missing_products)}")
    print(missing_products)

All collection sheet Item id exist in the Items id Sheet.

In [4]:
dfCollections

NameError: name 'dfCollections' is not defined

In [2]:
CollectoinSheetIds = dfCollections["Item Id"]
CollectoinSheetIds

NameError: name 'dfCollections' is not defined

In [1]:
ItemSheetIds =  dfItems["Id"].tolist()

NameError: name 'dfItems' is not defined

In [ ]:
ItemSheetIds
for eachId in CollectoinSheetIds:
    if eachId in ItemSheetIds:
        picture  = dfCollections.loc[dfCollections["Item Id"]==eachId,"Picture"]
        Barcode  = dfCollections.loc[dfCollections["Item Id"]==eachId,"Barcode"]
        Item_Name  = dfCollections.loc[dfCollections["Item Id"]==eachId,"Item Name"]
        Secondary_Item_Name  = dfCollections.loc[dfCollections["Item Id"]==eachId,"Secondary Item Name"]
        Price  = dfCollections.loc[dfCollections["Item Id"]==eachId,"Price"]

        Description  = dfItems.loc[dfItems["Id"]==eachId,"Description"]
        Secondary_Description  = dfItems.loc[dfItems["Id"]==eachId,"Secondary Description"]
        Menu  = dfItems.loc[dfItems["Id"]==eachId,"Menu"]
        Brand  = dfItems.loc[dfItems["Id"]==eachId,"Brand"]
        Secondary_Brand  = dfItems.loc[dfItems["Id"]==eachId,"Secondary Brand"]
        currentrowNumber = len(dfItems["Id"])
        dfItems.loc[currentrowNumber] = [picture,eachId,Item_Name,Secondary_Item_Name,Barcode,"NAN",Price,Description,Secondary_Description,Menu,Brand,Secondary_Brand,False]
        print("Matched"+" "+str(eachId)+" "+str(currentrowNumber))

    else:
        print("Not Matched")