In [3]:
from random import choice

import pandas as pd

series = pd.Series(["Ahsan","Python","Class"])
series

0     Ahsan
1    Python
2     Class
dtype: str

In [3]:
series2 = pd.Series(["Ahsan","Python","Class"],index=["^_^","^_-","-_^"])
series2

^_^     Ahsan
^_-    Python
-_^     Class
dtype: str

In [4]:
Raw_data = {"name":["Ahsan", "Pyhton","Class"], "age":[25,26,27]}
Raw_data

{'name': ['Ahsan', 'Pyhton', 'Class'], 'age': [25, 26, 27]}

In [7]:
df = pd.DataFrame(Raw_data)
df

     name  age
0   Ahsan   25
1  Pyhton   26
2   Class   27

In [8]:
df.to_csv("ClassFirdtTable.csv")

In [4]:
dfItems = pd.read_excel("vendorProducts.xlsx",sheet_name="Items")
dfCollections = pd.read_excel("vendorProducts.xlsx",sheet_name="Collections")

In [5]:
dfItems

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل,"Pleasure Lip Oil 001, 5 ml",8011607402304,NaN,"25,000د.ع","زيت مغذي للشفاه, يُعزز لمعان الشفاه بتأثير بصر...",Nourishing lip oil that enhances lip shine wit...,|بوبا ميلانو|Pupa Milano|Lip Oil|زيت الشفاه|زي...,NaN,العناية بالبشرة‎ -> الشفاه‎ -> زيوت,بوبا ميلانو,Pupa Milano,No
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,NaN,"300,000د.ع",عطر أروماتك إنيق للرجال.\nمكونات العطر: العنبر...,An elegant aromatic fragrance for men.\nFragra...,|شانيل|Chanel|العطور|Perfumes|عطر للرجال|عطر ر...,NaN,"العطور‎ -> رجالي‎ -> العطور,private group‎ -> ...",شانيل,Chanel,Yes
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل,Seapuri Scalpy Hair Serum 20 ml,8809934860870,NaN,"30,000د.ع",سيروم خفيف الوزن وغير دهني يعالج تساقط الشعر و...,"A lightweight, non greasy serum that treats ha...",|Others|اخرى|hair loss Serum|سيروم تساقط الشعر...,NaN,الشعر‎ -> العناية بالشعر‎ -> تساقط الشعر‎ -> س...,اخرى,Others,No
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل,Ganymede EDP 50 ml,3770006409141,NaN,00د.ع,"عطر شرقي حار للجنسين.\nمقدمة العطر: البخور, ال...",An oriental spicy fragrance for both sexes.\nT...,|Marc-Antoine Barois Paris|مارك أنطوان باروا ب...,NaN,"العطور‎ -> نسائي‎ -> العطور,العطور‎ -> رجالي‎ ...",مارك انطوان باروا باريس,Marc-Antoine Barrois Paris,No
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل,Brow Styling Gel With Peptides 15 ml,8056814230036,NaN,"15,000د.ع",امنحي حواجبك شكلاً أنيقًا يدوم طوال اليوم مع ج...,"Give your brows a sleek, all day shape with ou...",|Ayten|أيتن|Eyebrow Gel|جل الحواجب|جل تصفيف ال...,NaN,المكياج‎ -> الحواجب‎ -> جل,آيتن,Ayten,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,"16,500د.ع","زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,"12,000د.ع","رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,"10,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,"15,000د.ع","رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,"22,500د.ع","ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [6]:
dfCollections

,Item Id,Item Name,Secondary Item Name,Color Code,Price,Barcode,Code,Color,Secondary Color,Size,Unit Level,Is Active,Picture
0,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"420,000د.ع",3145891072204,82528.0,100 مل,100 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
1,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد,Bleu De Chanel L'Exclusif Parfum,NaN,"300,000د.ع",3145891072105,82755.0,50 مل,50 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
2,364804,هايلايتر ستك,The Glow Stick,#F3D5C6,"19,750د.ع",7333352079169,82570.0,24 سباركلينج بيج,24 Sparkling Beige,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
3,364804,هايلايتر ستك,The Glow Stick,#F2B2B9,"19,750د.ع",7333352079176,82571.0,25 روز جليم,25 Rose Gleam,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
4,364793,كونتور ستك,The Contour Stick,#AF8E7A,"19,750د.ع",7333352079084,82565.0,30,30,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14481,332027,كونسيلر فوري مضاد للشيخوخة 6 مل,Instant Anti Age Eraser Concealer 6 ml,#F5D4C5,"17,250د.ع",3600530733866,58724.0,03 معتدل,03 Fair,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14482,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"17,000د.ع",697029058770,60467.0,500 مل,500 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14483,316612,غسول الفم للثة الصحية بالنعناع النقي,Healthy Gums Mouthwash Pure Mint,NaN,"6,500د.ع",697029602478,81429.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...
14484,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"17,000د.ع",697029041260,47028.0,500 مل,500 ml,NaN,Level1,True,NaN
14485,316610,غسول فم منعش بالنعناع الخفيف,Fresh Breath Oral Rinse Mild Mint,NaN,"6,500د.ع",697029532409,81431.0,88.7 مل,88.7 ml,NaN,Level1,True,https://www.storeakmedia.com/storeak-erp/Store...

In [7]:
dfItems["Price"]

0         25,000د.ع
1        300,000د.ع
2         30,000د.ع
3             00د.ع
4         15,000د.ع
            ...
24697     16,500د.ع
24698     12,000د.ع
24699     10,500د.ع
24700     15,000د.ع
24701     22,500د.ع
Name: Price, Length: 24702, dtype: str

In [9]:
dfItems['Price'] = dfItems['Price'].str.replace(r'\D', '', regex=True).astype(int)

In [11]:
dfItems["Price"]

0         25000
1        300000
2         30000
3             0
4         15000
          ...
24697     16500
24698     12000
24699     10500
24700     15000
24701     22500
Name: Price, Length: 24702, dtype: int64

In [12]:
dfItems.info()

<class 'pandas.DataFrame'>
RangeIndex: 24702 entries, 0 to 24701
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Picture                    24300 non-null  str
 1   Id                         24702 non-null  int64
 2   Name                       24702 non-null  str
 3   Secondary Name             24702 non-null  str
 4   Barcode                    22041 non-null  str
 5   Code                       21993 non-null  str
 6   Price                      24702 non-null  int64
 7   Description                24645 non-null  str
 8   Secondary Description      24644 non-null  str
 9   Sub Description            24601 non-null  str
 10  Secondary Sub Description  4 non-null      str
 11  Menu                       24699 non-null  str
 12  Brand                      24699 non-null  str
 13  Secondary Brand            24696 non-null  str
 14  Has Collections            24702 non-null  str
dtypes: int64(2), str(13)
memory usage: 2.8 MB

In [13]:
dfItems.tail()

,Picture,Id,Name,Secondary Name,Barcode,Code,Price,Description,Secondary Description,Sub Description,Secondary Sub Description,Menu,Brand,Secondary Brand,Has Collections
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل,Lime & Matcha Hair & Body Mist 150 ml,5028197838058,0,16500,"زذاذ معطر الجسم والشعر منعش وفواح, يتكون من مز...","A refreshing and fragrant body and hair mist, ...",|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل,Pink Pepper & Lychee Hair & Body Mist 150 ml,5028197930516,0,12000,"رذاذ معطر الجسم والشعر جذاب ومنعش للنساء, يمتا...",An attractive and refreshing body and hair mis...,|ذا بودي شوب|The Body Shop|عطور الشعر|Hair Per...,NaN,العطور‎ -> نسائي‎ -> عطور الشعر,ذا بودي شوب,The Body Shop,No
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل,Glam & Doll Boost Lash Growth Volume Mascara 8 ml,4059729191380,0,10500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...","Mascara features a brush with thick bristles, ...",|كاتريس|Catrice|ماسكارا عادية| Mascara‎ Normal...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,كاتريس,Catrice,No
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل,Body Mist Passion Fruit150 ml,5283024103017,0,15000,"رذاذ معطر للجسم, يساعدك على الشعور بالانتعاش و...",A body mist that helps you feel fresh and conf...,|بيت الصابون اللبناني|Bayt Al Saboun|العناية ب...,NaN,"العناية بالجسم‎ -> سبلاش,private group‎ -> مين...",بيت الصابون اللبناني,Bayt Al Saboun,No
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل,Volume Supreme Mascara (1Black) 15 ml,4052136039429,0,22500,"ماسكارا تتميز بفرشاتها ذات الشعيرات الكثيفة, ت...",Mascara is characterized by its thick bristled...,|آرتديكو|Artdeco|ماسكارا عادية| Mascara‎ Norma...,NaN,المكياج‎ -> العيون‎ -> ماسكارا‎ -> العادي,آرتديكو,Artdeco,No

In [15]:
dfItems[["Picture","Id","Name"]]

,Picture,Id,Name
0,https://www.storeakmedia.com/storeak-erp/Store...,390188,زيت الشفاه بليجر 001، 5 مل
1,https://www.storeakmedia.com/storeak-erp/Store...,390187,عطر بلو دي شانيل لي اكسكلوسيف الجديد
2,https://www.storeakmedia.com/storeak-erp/Store...,390186,سيروم الشعر لفروة الرأس سيابوري 20 مل
3,https://www.storeakmedia.com/storeak-erp/Store...,390185,عطر جانيميد اودي بارفيوم 50 مل
4,https://www.storeakmedia.com/storeak-erp/Store...,390177,جل تصفيف الحواجب مع الببتيدات 15 مل
...,...,...,...
24697,https://www.storeakmedia.com/storeak-erp/Store...,315019,معطر الشعر والجسم بالليمون والماتشا 150 مل
24698,https://www.storeakmedia.com/storeak-erp/Store...,315018,معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل
24699,https://www.storeakmedia.com/storeak-erp/Store...,314993,ماسكارا جلام اند دول تعزز نمو الرموش 8 مل
24700,https://www.storeakmedia.com/storeak-erp/Store...,314992,مست الجسم باشن فروت 150 مل
24701,https://www.storeakmedia.com/storeak-erp/Store...,314991,ماسكارا فائقة الكثافة (1أسود) 15 مل

In [16]:
dfItems[["Name"]].fillna("")

                                                   Name
0                            زيت الشفاه بليجر 001، 5 مل
1                  عطر بلو دي شانيل لي اكسكلوسيف الجديد
2                 سيروم الشعر لفروة الرأس سيابوري 20 مل
3                        عطر جانيميد اودي بارفيوم 50 مل
4                   جل تصفيف الحواجب مع الببتيدات 15 مل
...                                                 ...
24697        معطر الشعر والجسم بالليمون والماتشا 150 مل
24698  معطر الشعر والجسم بالفلفل الوردي والليتشي 150 مل
24699         ماسكارا جلام اند دول تعزز نمو الرموش 8 مل
24700                        مست الجسم باشن فروت 150 مل
24701               ماسكارا فائقة الكثافة (1أسود) 15 مل

[24702 rows x 1 columns]

In [19]:
#make a data frame of userName / Age / Class
#save File as UserData.csv
UserName = {
  'name': ["Ahsan", "Ahmed", "Abdullah"],
  'age': [31, 17, 22],
  'class':["A1","A2","A3"]
}

myData = pd.DataFrame(UserName)

myData

       name  age class
0     Ahsan   31    A1
1     Ahmed   17    A2
2  Abdullah   22    A3

In [23]:
myData.to_csv("UserName.csv",index=False)

In [25]:
myData = pd.read_csv('UserName.csv')
myData

       name  age class
0     Ahsan   31    A1
1     Ahmed   17    A2
2  Abdullah   22    A3

In [27]:
newNameAdd = len(myData['name'])
newNameAdd.to_csv

3

In [ ]:
#Create Banking System
#Ask User to create Account or Check or withdraw or deposit
#Use while true for this process
#let say user created account = 5000
#Dictionary Example = {"UserNames"[a,b,c,d,e],"Age":[1,2,3,4],"Balance":[1000,2000,3000,4}}
#Create a csv and store data in there

In [28]:
BankApp = {"UserNames":["Ahsan","Ahmed","Abdullah"],
           "Age":[31,17,22],
           "DefaultBalance": [5000,5000,5000]
}
bankData = pd.DataFrame(BankApp)
bankData

  UserNames  Age  DefaultBalance
0     Ahsan   31            5000
1     Ahmed   17            5000
2  Abdullah   22            5000

In [29]:
bankData.to_csv("BankData.csv",index=False)

In [ ]:
while True:
    action = input("Choose an action: (1) Check (2) Withdraw (3) Deposit (4) New Account (5) Exit:")
    if action == "5":
        print("Saving the BankData")
        bankData.to_csv("BankData.csv",index=False)
        break
        name = input("Enter User Name: ")
        if name in bankData['UserNames'].values:
            user = bankData[bankData['UserNames'] == name].index()
            if choice == "1":
                print(f"")
            if choice == "2":
                print(f"")
            if choice == "3":
                print(f"")
            if choice == "4":
                print(f"")

In [1]:
import pandas as pd
StudentAccountDictionary = {"StudentId":["10001","10002","10003"],"StudentName":["Ahmad","Ali","yth"],"StudentClass":["1","2","3"],"Subjects":[["Math","English","Science"],["Math","Chemistry","Science"],["islamicStudies","English","Physics"]]}

In [2]:
studentDF = pd.DataFrame(StudentAccountDictionary)
studentDF

  StudentId StudentName StudentClass                            Subjects
0     10001       Ahmad            1            [Math, English, Science]
1     10002         Ali            2          [Math, Chemistry, Science]
2     10003         yth            3  [islamicStudies, English, Physics]

In [3]:
studentDF.to_csv("StudentData.csv",index=False)

In [4]:
while True:
    choice = input("Enter 1 for Student Registration \n Enter 2 for Student Information Fetch \n Enter 3 for Student Information Update \n Enter 4 for Exit:")
    if choice == "1":
        print("Student Registration")
    elif choice =="2":
        print("======Student Information Fetch========")
        studentDF = pd.read_csv("StudentData.csv")
        studentId = int(input("Enter Student Id:"))
        if studentId not in list(studentDF["StudentId"]):
            print("Student Id Not Found")
            continue
        for i in range(len(studentDF)):
            if studentDF["StudentId"][i] == studentId:
                print(f"Student Name : {studentDF['StudentName'][i]}")
                print(f"Student Class : {studentDF['StudentClass'][i]}")
                print(f"Student Subjects : {studentDF['Subjects'][i]}")
        print("======Student Information Fetch========")
    elif choice =="3":
        print("======Student Information Update=======")
        studentDF = pd.read_csv("StudentData.csv")
        studentId = int(input("Enter Student Id:"))
        if studentId not in list(studentDF["StudentId"]):
            print("Student Id Not Found")
            continue
        for i in range(len(studentDF)):
            if studentDF["StudentId"][i] == studentId:
                print("What do you want to update?")
                updateChoice = input("Enter 1 for Student Name \n Enter 2 for Student Class \n Enter 3 for Student Subjects:")
                if updateChoice == "1":
                    newStudentName = input("Enter New Student Name:")
                    studentDF['StudentName'][i] = newStudentName
                    print(f"Student Name Updated to {newStudentName}")
                elif updateChoice == "2":
                    newStudentClass = input("Enter New Student Class:")
                    studentDF['StudentClass'][i] = newStudentClass
                    print(f"Student Class Updated to {newStudentClass}")
                elif updateChoice == "3":
                    print("Enter Subjects")

    elif choice =="4":
        print("Exiting")
        break

======Student Information Fetch========
Student Name : yth
Student Class : 3
Student Subjects : ['islamicStudies', 'English', 'Physics']
======Student Information Fetch========

KeyboardInterrupt: Interrupted by user